log_level="TRACE"

[testdict]
second="ha ha"

[check]
test="this is an override in pycli.toml"

##
##
[pycli2.testdict]
this="is a test dictionary"
second="ho ho"

[slides]
screen_id=0
image_folder="C:\\"
