<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Processing the XLSX</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="scanner_files/libs/clipboard/clipboard.min.js"></script>
<script src="scanner_files/libs/quarto-html/quarto.js"></script>
<script src="scanner_files/libs/quarto-html/popper.min.js"></script>
<script src="scanner_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="scanner_files/libs/quarto-html/anchor.min.js"></script>
<link href="scanner_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="scanner_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="scanner_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="scanner_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="scanner_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


<link rel="stylesheet" href="styles.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#cmsc-courses-in-the-bulletin" id="toc-cmsc-courses-in-the-bulletin" class="nav-link active" data-scroll-target="#cmsc-courses-in-the-bulletin">CMSC Courses in the Bulletin</a></li>
  <li><a href="#course-descriptions-with-restrictions" id="toc-course-descriptions-with-restrictions" class="nav-link" data-scroll-target="#course-descriptions-with-restrictions">Course Descriptions with Restrictions</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Processing the XLSX</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>A list of CMSC courses was downloaded from the <a href="http://bulletin.vcu.edu/azcourses/cmsc/">campus bulletin</a>.</p>
<p>The list was loaded into XLSX and cleaned. The following sections provide a view of the CMSC courses from the Bulletin.</p>
<p>The script below loads the cleaned XLSX.</p>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> IPython.display <span class="im">import</span> Markdown</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tabulate <span class="im">import</span> tabulate</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>filename <span class="op">=</span> <span class="st">"cmsc-bulletin-spring-2023.xlsx"</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>xlsx <span class="op">=</span> pd.ExcelFile( filename )</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>df1 <span class="op">=</span> pd.read_excel(xlsx,<span class="st">"CMSC-Courses"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<p>Here is a list of columns:<br>‘Subject’, ‘Number’, ‘ID’, ‘Title’, ‘Hours’, ‘Catalog’, ‘Catalog Description’, ‘Restrictions’, ‘Isolated Description’.</p>
</div>
</div>
<section id="cmsc-courses-in-the-bulletin" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-courses-in-the-bulletin">CMSC Courses in the Bulletin</h2>
<div class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<p><a href="#tbl-table1">Table&nbsp;1</a> presents a list of CMSC courses in the bulletin. There are 82 courses in the bulletin.</p>
</div>
<div class="cell-output cell-output-display" data-execution_count="236">
<div id="tbl-table1" class="anchored">
<table class="table table-sm table-striped">
<caption>Table&nbsp;1: List of courses</caption>
<thead>
<tr class="header">
<th style="text-align: left;">ID</th>
<th style="text-align: left;">Title</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;101</td>
<td style="text-align: left;">Introduction to Computer Science</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;144</td>
<td style="text-align: left;">Code Beats With Python</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;191</td>
<td style="text-align: left;">Topics in Computer Science</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;210</td>
<td style="text-align: left;">Computers and Programming</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;245</td>
<td style="text-align: left;">Introduction to Programming Using C++</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;246</td>
<td style="text-align: left;">Advanced Programming Using C++</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;254</td>
<td style="text-align: left;">Introduction to Problem-solving</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;255</td>
<td style="text-align: left;">Introduction to Programming</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;256</td>
<td style="text-align: left;">Data Structures and Object Oriented Programming</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;257</td>
<td style="text-align: left;">Computer Systems</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;302</td>
<td style="text-align: left;">Introduction to Discrete Structures</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;303</td>
<td style="text-align: left;">Introduction to the Theory of Computation</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;311</td>
<td style="text-align: left;">Computer Organization</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;312</td>
<td style="text-align: left;">Introduction to Operating Systems</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;320</td>
<td style="text-align: left;">Software Engineering and Web Development</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;330</td>
<td style="text-align: left;">Data Science Skills</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;340</td>
<td style="text-align: left;">Cybersecurity Skills</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;355</td>
<td style="text-align: left;">Fundamentals of Software Engineering</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;391</td>
<td style="text-align: left;">Topics in Computer Science</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;401</td>
<td style="text-align: left;">Algorithm Analysis with Advanced Data Structures</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;403</td>
<td style="text-align: left;">Programming Languages</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;404</td>
<td style="text-align: left;">Compiler Construction</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;409</td>
<td style="text-align: left;">Artificial Intelligence</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;410</td>
<td style="text-align: left;">Introduction to Quantum Computing</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;411</td>
<td style="text-align: left;">Computer Graphics</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;412</td>
<td style="text-align: left;">Social Network Analysis and Cybersecurity Risks</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;413</td>
<td style="text-align: left;">Introduction to Cybersecurity</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;414</td>
<td style="text-align: left;">Computer and Network Security</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;415</td>
<td style="text-align: left;">Introduction to Cryptography</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;416</td>
<td style="text-align: left;">Introduction to Natural Language Processing</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;420</td>
<td style="text-align: left;">Software Project Management</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;425</td>
<td style="text-align: left;">Introduction to Software Analysis and Testing</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;428</td>
<td style="text-align: left;">Mobile Programming: iOS</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;435</td>
<td style="text-align: left;">Introduction to Data Science</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;440</td>
<td style="text-align: left;">Data Communication and Networking</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;441</td>
<td style="text-align: left;">Senior Design Studio I (Laboratory/Project Time)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;442</td>
<td style="text-align: left;">Senior Design Studio II (Laboratory/Project Time)</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;451</td>
<td style="text-align: left;">Senior Project I</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;452</td>
<td style="text-align: left;">Senior Project II</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;455</td>
<td style="text-align: left;">Software as a Service</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;475</td>
<td style="text-align: left;">Design and Implementation of User Interfaces</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;491</td>
<td style="text-align: left;">Topics in Computer Science</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;492</td>
<td style="text-align: left;">Independent Study</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;501</td>
<td style="text-align: left;">Advanced Algorithms</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;502</td>
<td style="text-align: left;">Parallel Algorithms</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;506</td>
<td style="text-align: left;">Computer Networks and Communications</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;508</td>
<td style="text-align: left;">Database Theory</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;510</td>
<td style="text-align: left;">Regularization Methods for Machine Learning</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;512</td>
<td style="text-align: left;">Advanced Social Network Analysis and Security</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;516</td>
<td style="text-align: left;">Advanced Natural Language Processing</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;525</td>
<td style="text-align: left;">Introduction to Software Analysis, Testing and Verification</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;526</td>
<td style="text-align: left;">Theory of Programming Languages</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;531</td>
<td style="text-align: left;">3D Computer Vision for Robot Navigation</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;591</td>
<td style="text-align: left;">Topics in Computer Science</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;601</td>
<td style="text-align: left;">Convex Optimization</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;602</td>
<td style="text-align: left;">Operating Systems</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;603</td>
<td style="text-align: left;">High Performance Distributed Systems</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;605</td>
<td style="text-align: left;">Advanced Computer Architecture</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;608</td>
<td style="text-align: left;">Advanced Database</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;610</td>
<td style="text-align: left;">Algorithmic Foundations of Bioinformatics</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;611</td>
<td style="text-align: left;">Computer Multimedia</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;612</td>
<td style="text-align: left;">Game Theory and Security</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;615</td>
<td style="text-align: left;">Cryptocurrency and Blockchain Techniques</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;618</td>
<td style="text-align: left;">Database and Application Security</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;619</td>
<td style="text-align: left;">The Design and Specifications of User Interfaces</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;620</td>
<td style="text-align: left;">Applied Cryptography</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;621</td>
<td style="text-align: left;">Theory of Computation</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;622</td>
<td style="text-align: left;">Network and System Security</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;623</td>
<td style="text-align: left;">Cloud Computing</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;624</td>
<td style="text-align: left;">Software Quality Assurance</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;625</td>
<td style="text-align: left;">Advanced Software Analysis, Testing and Verification</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;628</td>
<td style="text-align: left;">Mobile Networks: Applications, Modeling and Analysis</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;630</td>
<td style="text-align: left;">Image Analysis</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;635</td>
<td style="text-align: left;">Knowledge Discovery and Data Mining</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;636</td>
<td style="text-align: left;">Artificial Neural Networks and Deep Learning</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;654</td>
<td style="text-align: left;">Memory and Malware Forensics</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;678</td>
<td style="text-align: left;">Statistical Learning and Fuzzy Logic Algorithms</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;691</td>
<td style="text-align: left;">Special Topics in Computer Science</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;692</td>
<td style="text-align: left;">Independent Study</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;697</td>
<td style="text-align: left;">Directed Research</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CMSC&nbsp;701</td>
<td style="text-align: left;">Research Methods</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMSC&nbsp;702</td>
<td style="text-align: left;">Computer Science Seminar</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="course-descriptions-with-restrictions" class="level1">
<h1>Course Descriptions with Restrictions</h1>
<p>The section below uses the panda dataframe from above and lists out courses, restrictions, and descriptions.</p>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Display each course using markdown.</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">## The entire block of markdown is created and rendered.</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co">## There can be only one "display(Markdown())" call per code block.</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co">## The spacing is expanded to accomodate the Markdown processor.</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>block <span class="op">=</span> <span class="st">""</span><span class="op">;</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> index, row <span class="kw">in</span> df1.iterrows():</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  block <span class="op">=</span> block <span class="op">+</span> <span class="ss">f"""</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="ss">## </span><span class="sc">{</span>row[<span class="st">"ID"</span>]<span class="sc">}</span><span class="ss"> - </span><span class="sc">{</span>row[<span class="st">"Title"</span>]<span class="sc">}</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="ss">   </span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="ss">**Restrictions:** </span><span class="sc">{</span>row[<span class="st">"Restrictions"</span>]<span class="sc">}</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="ss">**Description:** </span><span class="sc">{</span>row[<span class="st">"Isolated Description"</span>]<span class="sc">}</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="ss">"""</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>display(Markdown( block ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<section id="cmsc-101---introduction-to-computer-science" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-101---introduction-to-computer-science">CMSC&nbsp;101 - Introduction to Computer Science</h2>
<p><strong>Restrictions:</strong> MATH&nbsp;139&nbsp;or&nbsp;MATH&nbsp;141&nbsp;with a minimum grade of C.</p>
<p><strong>Description:</strong> An introduction to the work of computer scientists, including an overview of current research and application areas as well as career opportunities. Topics include problem-solving, the basics of computer organization, the software engineering life cycle, research resources and social and ethical aspects of technology. Additional topics also include binary, hexadecimal, two’s complement, floating point representation, ASCII and Unicode.</p>
</section>
<section id="cmsc-144---code-beats-with-python" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-144---code-beats-with-python">CMSC&nbsp;144 - Code Beats With Python</h2>
<p><strong>Restrictions:</strong> (none)</p>
<p><strong>Description:</strong> An introduction to computer programming in Python by teaching students to create hip hop beats. Teaches fundamental programming concepts including sequencing, syntax, variables, functions, parameters, lists, repetition and modularization. Teaches just enough music theory to ensure that student-made beats sound great, including fundamental concepts such as melody, rhythm, harmony, chord progression and orchestration. Students will complete in-class activities that reinforce class concepts and, if completed correctly, demonstrate a clear understanding of the material.</p>
</section>
<section id="cmsc-191---topics-in-computer-science" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-191---topics-in-computer-science">CMSC&nbsp;191 - Topics in Computer Science</h2>
<p><strong>Restrictions:</strong> permission of the instructor.</p>
<p><strong>Description:</strong> This course will teach selected topics in computer science. See the Schedule of Classes for specific topics to be offered each semester and prerequisites.</p>
</section>
<section id="cmsc-210---computers-and-programming" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-210---computers-and-programming">CMSC&nbsp;210 - Computers and Programming</h2>
<p><strong>Restrictions:</strong> (none)</p>
<p><strong>Description:</strong> Introduction to object-oriented programming using Python. The course introduces students to structured programming logic and design techniques. The course content also includes instruction in critical thinking and problem-solving skills using contemporary tools. Specific topics include flowcharting, pseudocode and program control structures, including sequence, selection and repetition. This course is not applicable for credit toward the BS in Computer Science.</p>
</section>
<section id="cmsc-245---introduction-to-programming-using-c" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-245---introduction-to-programming-using-c">CMSC&nbsp;245 - Introduction to Programming Using C++</h2>
<p><strong>Restrictions:</strong> MATH&nbsp;151&nbsp;or satisfactory score on the Mathematical Placement Test. Students registering for&nbsp;CMSC&nbsp;245&nbsp;must have taken the VCU Mathematics Placement Test within the one-year period immediately preceding the beginning of the course. An exception to this policy is made in the case in which the stated alternative prerequisite course has been completed at VCU. Students are expected to have fundamental computer skills.</p>
<p><strong>Description:</strong> Introduction to the concepts and practice of structured programming using C++. Problem-solving, top-down design of algorithms, objects, basic C++ syntax, control structures, functions and arrays. This course is intended for engineering majors.</p>
</section>
<section id="cmsc-246---advanced-programming-using-c" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-246---advanced-programming-using-c">CMSC&nbsp;246 - Advanced Programming Using C++</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;245.</p>
<p><strong>Description:</strong> Advanced programming in C++. Topics include program design, objects, classes, inheritance, files, strings, linked lists, stacks, queues, binary trees, recursion, and basic searching and sorting techniques. This course is intended for engineering majors.</p>
</section>
<section id="cmsc-254---introduction-to-problem-solving" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-254---introduction-to-problem-solving">CMSC&nbsp;254 - Introduction to Problem-solving</h2>
<p><strong>Restrictions:</strong> (none)</p>
<p><strong>Description:</strong> Introduction to problem solving and implementation of solutions using Python. The course introduces students to concepts and practice of structured programming, problem-solving, top-down design of algorithms, a Python language syntax, control structures and arrays. The course content also includes instruction in critical-thinking and problem-solving skills using contemporary tools. Specific topics include flowcharting, pseudocode and program control structures, including sequence, selection, repetition and modularization.</p>
</section>
<section id="cmsc-255---introduction-to-programming" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-255---introduction-to-programming">CMSC&nbsp;255 - Introduction to Programming</h2>
<p><strong>Restrictions:</strong> calculus-level placement on the VCU Mathematics Placement Test within the one-year period immediately preceding enrollment in the course, or&nbsp;MATH&nbsp;151&nbsp;or equivalent. Students are expected to have fundamental computer skills.</p>
<p><strong>Description:</strong> Introduction to object-oriented programming using Java. Topics include problem-solving, top-down design of algorithms using control structures, methods, arrays, basic I/O, basic concepts of objects and classes in Java, Java classes for manipulating strings, and introduction to program testing, UML notation and integrated development environments. Students may not receive credit for both&nbsp;CMSC&nbsp;255&nbsp;and&nbsp;INFO&nbsp;250.</p>
</section>
<section id="cmsc-256---data-structures-and-object-oriented-programming" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-256---data-structures-and-object-oriented-programming">CMSC&nbsp;256 - Data Structures and Object Oriented Programming</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;255&nbsp;with a minimum grade of C; corequisite:&nbsp;CMSC&nbsp;302.</p>
<p><strong>Description:</strong> Advanced programming using Java. Topics include introduction to object-oriented design, inheritance, polymorphism, exceptions, interfaces, linked lists, stacks, queues, binary trees, recursion, and basic searching and sorting techniques. Continued focus on program testing and UML notation. Students may not receive credit for both&nbsp;CMSC&nbsp;256&nbsp;and&nbsp;INFO&nbsp;350.</p>
</section>
<section id="cmsc-257---computer-systems" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-257---computer-systems">CMSC&nbsp;257 - Computer Systems</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;256&nbsp;with a minimum grade of C.</p>
<p><strong>Description:</strong> Topics include UNIX essentials; system programming in C; machine-level representation and organization of programs/data, arrays and pointers; types, structs and unions; strings; bit/byte operations; memory management; shell programming; input/output, including file handling; debugging; signals; network programming using sockets; program concurrency using forks and threads; experiments on program performance and optimization techniques.</p>
</section>
<section id="cmsc-302---introduction-to-discrete-structures" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-302---introduction-to-discrete-structures">CMSC&nbsp;302 - Introduction to Discrete Structures</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;255&nbsp;with minimum grade of C.</p>
<p><strong>Description:</strong> Logic and proofs, sets, functions, sequences and sums, relations, graphs, trees, induction and recursion, advanced counting technique (recurrences).</p>
</section>
<section id="cmsc-303---introduction-to-the-theory-of-computation" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-303---introduction-to-the-theory-of-computation">CMSC&nbsp;303 - Introduction to the Theory of Computation</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;302&nbsp;or the equivalent with a grade of C or better.</p>
<p><strong>Description:</strong> Complexity classes, grammars, automata, formal languages, Turing machines, computability.</p>
</section>
<section id="cmsc-311---computer-organization" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-311---computer-organization">CMSC&nbsp;311 - Computer Organization</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;302&nbsp;with minimum grade of C; corequisite:&nbsp;CMSC&nbsp;257.</p>
<p><strong>Description:</strong> Introduction to the basic organization of computers including elementary digital logic design, processor and arithmetic/logic unit design, data paths, memory hierarchy, I/O devices, instruction set architecture and addressing modes.</p>
</section>
<section id="cmsc-312---introduction-to-operating-systems" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-312---introduction-to-operating-systems">CMSC&nbsp;312 - Introduction to Operating Systems</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;311&nbsp;or&nbsp;EGRE&nbsp;364.</p>
<p><strong>Description:</strong> Computer systems design, I/O processing, secondary memory organization, command languages, memory management and job scheduling. Students will work in teams to design and implement an operating system simulation.</p>
</section>
<section id="cmsc-320---software-engineering-and-web-development" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-320---software-engineering-and-web-development">CMSC&nbsp;320 - Software Engineering and Web Development</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;210.</p>
<p><strong>Description:</strong> Introduction to software engineering and web development. The course introduces students to the software development process, including design, development and testing principles. Students will apply these principles in the development of a web application. This course is not applicable for credit toward any College of Engineering degrees.</p>
</section>
<section id="cmsc-330---data-science-skills" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-330---data-science-skills">CMSC&nbsp;330 - Data Science Skills</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;210.</p>
<p><strong>Description:</strong> Introduction to data science skills. The course introduces students to the foundations of data science and the tools used to collect, analyze and represent data. Students will apply these principles in both analysis and visualization projects. This course is not applicable for credit toward any College of Engineering degrees.</p>
</section>
<section id="cmsc-340---cybersecurity-skills" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-340---cybersecurity-skills">CMSC&nbsp;340 - Cybersecurity Skills</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;210.</p>
<p><strong>Description:</strong> Introduction to cybersecurity skills. The course introduces students to cybersecurity terminology, standards and best practices. Students will apply these practices as part of a cybersecurity-focused project. This course is not applicable for credit toward any College of Engineering degrees.</p>
</section>
<section id="cmsc-355---fundamentals-of-software-engineering" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-355---fundamentals-of-software-engineering">CMSC&nbsp;355 - Fundamentals of Software Engineering</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;256&nbsp;or&nbsp;EGRE&nbsp;246, either with a minimum grade of C.</p>
<p><strong>Description:</strong> Provides an overview of how to engineer software systems, including all stages of the software development process based on agile principles. Familiarizes students with modern software tooling and the principles of software quality and testing. Students will work in teams to gain experience in software development methodology, write specification and design documents, and develop a prototype.</p>
</section>
<section id="cmsc-391---topics-in-computer-science" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-391---topics-in-computer-science">CMSC&nbsp;391 - Topics in Computer Science</h2>
<p><strong>Restrictions:</strong> permission of the instructor.</p>
<p><strong>Description:</strong> This course will teach selected topics in computer science. See the Schedule of Classes for specific topics to be offered each semester and prerequisites.</p>
</section>
<section id="cmsc-401---algorithm-analysis-with-advanced-data-structures" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-401---algorithm-analysis-with-advanced-data-structures">CMSC&nbsp;401 - Algorithm Analysis with Advanced Data Structures</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;256&nbsp;with a grade of C or better and&nbsp;CMSC&nbsp;302&nbsp;with a grade of C or better.</p>
<p><strong>Description:</strong> Introduction to algorithm analysis and complexity classes. Advanced data structures topics including multiple linked lists, height-balanced trees, B-trees, hashing and graph representation; incorporating data structures into object-oriented design. Analysis of various searching and sorting algorithms. Algorithm design topics include divide-and-conquer, dynamic programming and greedy methods.</p>
</section>
<section id="cmsc-403---programming-languages" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-403---programming-languages">CMSC&nbsp;403 - Programming Languages</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;256&nbsp;and&nbsp;CMSC&nbsp;303, both with a minimum grade of C.</p>
<p><strong>Description:</strong> Survey of representative modern programming languages. Formal definition of programming languages including specifications of syntax and semantics. Precedence, infix, prefix and postfix notation. Global properties of algorithmic languages. Sub-routines, co-routines and tasks. List processing, string manipulation, data description and simulation languages. Run-time representation of program and data structures.</p>
</section>
<section id="cmsc-404---compiler-construction" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-404---compiler-construction">CMSC&nbsp;404 - Compiler Construction</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;401&nbsp;and&nbsp;403.</p>
<p><strong>Description:</strong> A first course in compiler theory and construction. Formal description of languages, underlying theory and design techniques for compilers, lexical analysis, syntax analysis, syntax-directed translation, intermediate languages, run-time system management, code generation, code optimization, compiler-building tools.</p>
</section>
<section id="cmsc-409---artificial-intelligence" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-409---artificial-intelligence">CMSC&nbsp;409 - Artificial Intelligence</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;401&nbsp;with a minimum grade of C and&nbsp;MATH&nbsp;310.</p>
<p><strong>Description:</strong> Covers problem spaces, problem-solving methods, game playing, knowledge representatives, expert systems, natural language understanding.</p>
</section>
<section id="cmsc-410---introduction-to-quantum-computing" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-410---introduction-to-quantum-computing">CMSC&nbsp;410 - Introduction to Quantum Computing</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;401&nbsp;and&nbsp;MATH&nbsp;310, both with a minimum grade of B.</p>
<p><strong>Description:</strong> Introduction to quantum information processing: state vectors and density operators, tensor product space, unitary evolution, no-go theorems, measurement, qubit, gate model of quantum computing, quantum complexity theory, quantum error correction, quantum algorithms, and quantum machine learning.</p>
</section>
<section id="cmsc-411---computer-graphics" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-411---computer-graphics">CMSC&nbsp;411 - Computer Graphics</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;355&nbsp;and&nbsp;MATH&nbsp;310.</p>
<p><strong>Description:</strong> Presents mathematical techniques for graphic development and transformation, curve and surface approximation and projections, graphical languages and data structures and their implementation, graphic modeling.</p>
</section>
<section id="cmsc-412---social-network-analysis-and-cybersecurity-risks" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-412---social-network-analysis-and-cybersecurity-risks">CMSC&nbsp;412 - Social Network Analysis and Cybersecurity Risks</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;401&nbsp;with a minimum grade of C.</p>
<p><strong>Description:</strong> Covers network models, link prediction and analysis, centrality measures, random networks, power-laws and preferential attachment, small world phenomenon and decentralized search, community structure, information propagation in networks, and security and privacy issues in OSNs.</p>
</section>
<section id="cmsc-413---introduction-to-cybersecurity" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-413---introduction-to-cybersecurity">CMSC&nbsp;413 - Introduction to Cybersecurity</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;401&nbsp;with a minimum grade of C.</p>
<p><strong>Description:</strong> This course provides introduction and basic concepts of computer security, cyber attacks, cyber defense, cyber forensics and cyber ethics.</p>
</section>
<section id="cmsc-414---computer-and-network-security" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-414---computer-and-network-security">CMSC&nbsp;414 - Computer and Network Security</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;401&nbsp;with a minimum grade of C. Corequisite:&nbsp;CMSC&nbsp;312.</p>
<p><strong>Description:</strong> This course covers the best practices of computer systems and network security. Key topics include security architecture, cryptographic systems and security management tools.</p>
</section>
<section id="cmsc-415---introduction-to-cryptography" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-415---introduction-to-cryptography">CMSC&nbsp;415 - Introduction to Cryptography</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;401&nbsp;with a minimum grade of C.</p>
<p><strong>Description:</strong> This course provides a rigorous and theoretical introduction to modern cryptography. Key topics include symmetric key encryption and authentication, public key encryption, and digital signatures.</p>
</section>
<section id="cmsc-416---introduction-to-natural-language-processing" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-416---introduction-to-natural-language-processing">CMSC&nbsp;416 - Introduction to Natural Language Processing</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;401&nbsp;with a minimum grade of C.</p>
<p><strong>Description:</strong> Covers rule-based and statistical methods for creating computer programs that analyze, generate and understand human language. Topics include regular expressions and automata, context-free grammars, probabilistic classifiers, and machine learning. Word-level, syntactic and semantic processing are all considered. Application to real-world problems such as spell-checking, Web search, automatic question answering, authorship identification and developing conversational interfaces.</p>
</section>
<section id="cmsc-420---software-project-management" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-420---software-project-management">CMSC&nbsp;420 - Software Project Management</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;355&nbsp;with a minimum grade of C.</p>
<p><strong>Description:</strong> Study of the logistics of team software development. Students work in teams to gain experience in software management and develop the components of a larger software product. Topics include risk management, project planning, quality management, configuration management and software testing.</p>
</section>
<section id="cmsc-425---introduction-to-software-analysis-and-testing" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-425---introduction-to-software-analysis-and-testing">CMSC&nbsp;425 - Introduction to Software Analysis and Testing</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;355&nbsp;with a minimum grade of C. Enrollment is restricted to majors in the computer science program.</p>
<p><strong>Description:</strong> A practical introduction to testing complex software applications. An introduction to concepts and techniques used in the analysis of software, including basic and advanced control flow and data flow analyses. Using analytic results to derive test data and validate the correct implementation of programs. Advanced testing strategies including random, structural, mutation and fuzzing.</p>
</section>
<section id="cmsc-428---mobile-programming-ios" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-428---mobile-programming-ios">CMSC&nbsp;428 - Mobile Programming: iOS</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;355, with a minimum grade of C.</p>
<p><strong>Description:</strong> This course covers the fundamentals of Swift, Xcode and iOS for programming and design of iOS applications. Background in object-oriented programming and access to a computer with Xcode platform is required.</p>
</section>
<section id="cmsc-435---introduction-to-data-science" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-435---introduction-to-data-science">CMSC&nbsp;435 - Introduction to Data Science</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;401&nbsp;with a minimum grade of C.</p>
<p><strong>Description:</strong> This course covers understanding, representation, storage, retrieval, preprocessing and analysis of data. Specific topics include data quality and preprocessing, database management systems, data warehouses, selected methods for scalable unsupervised and supervised data analysis, and assessment of results generated by these methods. Students will be engaged in analysis of real-life data from data preprocessing, through data analysis, to the assessment of a knowledge product.</p>
</section>
<section id="cmsc-440---data-communication-and-networking" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-440---data-communication-and-networking">CMSC&nbsp;440 - Data Communication and Networking</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;257&nbsp;with a minimum grade of C. Enrollment is restricted to majors in the College of Engineering.</p>
<p><strong>Description:</strong> This course explores computer networking, focusing on the applications and protocols that run on the Internet. Students will take a top-down approach to the layered network architecture, studying applications first and then proceeding down the network “stack” toward the physical link. Students will examine the operation of applications such as the web, FTP, e-mail and DNS. At the transport layer, students will study both connectionless UDP and connection-oriented TCP, with an in-depth study of TCP operation, specifically flow control and congestion control. Data communications are explored through various data routing protocols. Additional topics include network security and wireless/mobile networking.</p>
</section>
<section id="cmsc-441---senior-design-studio-i-laboratoryproject-time" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-441---senior-design-studio-i-laboratoryproject-time">CMSC&nbsp;441 - Senior Design Studio I (Laboratory/Project Time)</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;355; and&nbsp;UNIV&nbsp;200&nbsp;or&nbsp;HONR&nbsp;200&nbsp;or equivalent, both with minimum grades of C. Corequisite:&nbsp;CMSC&nbsp;451. Enrollment is restricted to computer science majors with senior standing who have 24 credits in computer science courses.</p>
<p><strong>Description:</strong> A minimum of six laboratory hours per week dedicated to the execution phase of the senior design (capstone) project for the computer science major. Tasks include team meetings, brainstorming, sponsor advising, researching, designing, implementing, reviewing, testing and validating projects. Each student will participate, either individually or as part of a team, in a project or other experience approved by the course coordinator or sponsored by another computer science faculty member. Students will submit a detailed written description of their proposed project or experience and will present orally some aspect of what they have learned and/or done during the semester. This course cannot be counted as upper-level CMSC electives for students graduating under bullet</p>
</section>
<section id="cmsc-442---senior-design-studio-ii-laboratoryproject-time" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-442---senior-design-studio-ii-laboratoryproject-time">CMSC&nbsp;442 - Senior Design Studio II (Laboratory/Project Time)</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;441,&nbsp;CMSC&nbsp;451&nbsp;and&nbsp;CMSC&nbsp;508, each with a minimum grade of C. Corequisite:&nbsp;CMSC&nbsp;452. Enrollment is restricted to computer science majors with senior standing who have 24 credits in computer science courses.</p>
<p><strong>Description:</strong> A minimum of six laboratory hours per week dedicated to the execution phase of the senior design (capstone) project for the computer science major. Tasks include team meetings, brainstorming, sponsor advising, researching, designing, implementing, reviewing, testing and validating projects. Each student will participate, either individually or as part of a team, in a project or other experience approved by the course coordinator or sponsored by another computer science faculty member. Students must continue on the same project that was started in&nbsp;CMSC&nbsp;441&nbsp;and&nbsp;CMSC&nbsp;451. A final project report and presentation are due at the conclusion of the two-semester project or experience. This course cannot be counted as upper-level CMSC electives for students graduating under bulletins prio</p>
</section>
<section id="cmsc-451---senior-project-i" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-451---senior-project-i">CMSC&nbsp;451 - Senior Project I</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;355&nbsp;with minimum grade of C; and&nbsp;UNIV&nbsp;200&nbsp;or&nbsp;HONR&nbsp;200&nbsp;or equivalent. Corequisite:&nbsp;CMSC&nbsp;441. Enrollment is restricted to computer science majors with senior standing who have 24 credits in computer science courses.</p>
<p><strong>Description:</strong> This weekly seminar presents and discusses topics relevant to senior-level computer science students in support of the capstone project and upcoming graduation. A single course coordinator manages and administers the course and schedules the various faculty lectures and guest speakers. Topics include, but are not limited to, the following: proposal writing; project planning and management; scheduling resources and budgeting for software development projects; patents and intellectual property; entrepreneurship; ethical, legal and social issues in computing; and professional responsibilities of computer scientists. Each student will write and revise a research paper on a technical topic associated with his or her project or experience. A final project report and presentat</p>
</section>
<section id="cmsc-452---senior-project-ii" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-452---senior-project-ii">CMSC&nbsp;452 - Senior Project II</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;441,&nbsp;CMSC&nbsp;451&nbsp;and&nbsp;CMSC&nbsp;508, each with a minimum grade of C. Corequisite:&nbsp;CMSC&nbsp;442. Enrollment is restricted to students with senior standing in the computer science department.</p>
<p><strong>Description:</strong> This weekly seminar presents and discusses topics relevant to senior-level computer science students in support of the capstone project and upcoming graduation. A single course coordinator manages and administers the course and schedules the various faculty lectures and guest speakers. Topics include, but are not limited to, the following: proposal writing; project planning and management; scheduling resources and budgeting for software development projects; patents and intellectual property; entrepreneurship; ethical, legal and social issues in computing; and professional responsibilities of computer scientists. Each student will write and revise a research paper on a technical topic associated with his or her project or experience. Students must continue on the same project that was started in&nbsp;CMSC&nbsp;451.</p>
</section>
<section id="cmsc-455---software-as-a-service" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-455---software-as-a-service">CMSC&nbsp;455 - Software as a Service</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;355&nbsp;with a minimum grade of C. Enrollment is restricted to majors in the computer science program.</p>
<p><strong>Description:</strong> Students will examine the challenges, opportunities and open problems of software-as-a-service deployed on commodity cloud computing platforms. Covers relevant software architectures and API design principles. Includes concepts of modern software frameworks for software development, cloud computing for software deployment and software operations. Students participate in projects that use modern tooling to develop, deploy and monitor a software application.</p>
</section>
<section id="cmsc-475---design-and-implementation-of-user-interfaces" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-475---design-and-implementation-of-user-interfaces">CMSC&nbsp;475 - Design and Implementation of User Interfaces</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;355&nbsp;with a minimum grade of C. Enrollment is restricted to majors in the computer science program.</p>
<p><strong>Description:</strong> This course investigates the design and implementation of user interfaces and the evaluation of user experiences. Particular emphasis is placed on creating professional-quality designs and implementations and on evaluating these implementations with end-users. Students will create their own UIs as well as critique others to develop a deep understanding of what works in practice.</p>
</section>
<section id="cmsc-491---topics-in-computer-science" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-491---topics-in-computer-science">CMSC&nbsp;491 - Topics in Computer Science</h2>
<p><strong>Restrictions:</strong> permission of instructor.</p>
<p><strong>Description:</strong> This course will cover selected topics in computer science. See the Schedule of Classes for specific topics to be offered each semester.</p>
</section>
<section id="cmsc-492---independent-study" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-492---independent-study">CMSC&nbsp;492 - Independent Study</h2>
<p><strong>Restrictions:</strong> (none)</p>
<p><strong>Description:</strong> Maximum 4 credits per semester; maximum total of 6 credits. Generally open only to students of junior or senior standing who have acquired at least 12 credits in the departmental discipline. Determination of the amount of credit and permission of instructor and department chair must be procured prior to registration of the course. The student must submit a proposal for investigating some area or problem not contained in the regular curriculum. The results of the student’s study will be presented in a report.</p>
</section>
<section id="cmsc-501---advanced-algorithms" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-501---advanced-algorithms">CMSC&nbsp;501 - Advanced Algorithms</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;401&nbsp;or equivalent. Enrollment is restricted to students with graduate standing or those accepted into the accelerated BS to MS program in computer science.</p>
<p><strong>Description:</strong> Advanced graph algorithms, advanced data structures, applied numerical algorithms, optimization methods, approximation methods for hard graph and string problems and computational geometry algorithms.</p>
</section>
<section id="cmsc-502---parallel-algorithms" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-502---parallel-algorithms">CMSC&nbsp;502 - Parallel Algorithms</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;312&nbsp;and&nbsp;CMSC&nbsp;401. Enrollment is restricted to students with graduate standing or those accepted into the accelerated BS to MS program in computer science.</p>
<p><strong>Description:</strong> Software and hardware mechanisms for providing mutual exclusion in uniprocessor and multiprocessor environments. Architectural issues including pipeline design, superscalar computers, multiprocessors, memory systems, peripherals, interfacing techniques, networks, performance and software issues. Design and uses of parallel algorithms to solve concurrency problems in a distributed environment including message passing and remote procedure calls. Students will work in teams (as well as on individual projects) to design and implement parallel algorithms.</p>
</section>
<section id="cmsc-506---computer-networks-and-communications" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-506---computer-networks-and-communications">CMSC&nbsp;506 - Computer Networks and Communications</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;312.</p>
<p><strong>Description:</strong> Theoretical and applied analysis of basic data communication systems; design of networks in the framework of the OSI reference model; Local and Wide Area Networks; performance analysis of networks; error control and security. Students will work in teams to design and implement a small computer network. Crosslisted as:&nbsp;EGRE&nbsp;526.</p>
</section>
<section id="cmsc-508---database-theory" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-508---database-theory">CMSC&nbsp;508 - Database Theory</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;303&nbsp;with a minimum grade of C.</p>
<p><strong>Description:</strong> Design and implementation of relational database systems. Emphasis is placed on entity-relationship diagrams, relational algebra, normal forms and normalization. Introduction to SQL. Discussion of physical level issues. Students will be required to complete a design project and give an oral presentation of the project. Not applicable toward the MS in Computer Science or the PHD in Engineering, computer science concentration.</p>
</section>
<section id="cmsc-510---regularization-methods-for-machine-learning" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-510---regularization-methods-for-machine-learning">CMSC&nbsp;510 - Regularization Methods for Machine Learning</h2>
<p><strong>Restrictions:</strong> Enrollment is restricted to students with graduate standing in computer science or related discipline such as bioinformatics or acceptance into the accelerated BS to MS program in computer science.</p>
<p><strong>Description:</strong> The course will assume undergraduate-level background in algorithms, linear algebra, calculus, statistics and probability. Upon successful completion of this course, the student will be able to understand recent advances in machine learning and apply machine-learning tools that go beyond learning from data, as well as have the ability to incorporate additional knowledge about the learning problem. Topics covered will include optimization-based view of supervised machine learning; classical regularization approaches including weight decay and Lasso; regularization terms incorporating additional knowledge about structures in the feature space, including group lasso and graph-based regularization terms; semi-supervised learning using graphs linking unlabeled and labeled samples.</p>
</section>
<section id="cmsc-512---advanced-social-network-analysis-and-security" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-512---advanced-social-network-analysis-and-security">CMSC&nbsp;512 - Advanced Social Network Analysis and Security</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;412&nbsp;and&nbsp;CMSC&nbsp;501. Enrollment is restricted to students with graduate standing in computer science or a related discipline such as bioinformatics or acceptance into the accelerated BS to MS program in computer science.</p>
<p><strong>Description:</strong> The purpose of the course is to teach algorithms for analyzing social networks and complex systems. The focus will be on understanding the inner workings of algorithms using in-network analysis and security threats in online social network sites. Topic covered will include modeling social and technological networks, methods for analyzing structure and dynamical processes on the network, and security and privacy issues in online social networks such as inference attacks, network anonymization, sybil attacks and defense, social bots.</p>
</section>
<section id="cmsc-516---advanced-natural-language-processing" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-516---advanced-natural-language-processing">CMSC&nbsp;516 - Advanced Natural Language Processing</h2>
<p><strong>Restrictions:</strong> Enrollment is restricted to students with graduate standing in computer science or a related discipline, or those accepted into the accelerated BS to MS program in computer science.</p>
<p><strong>Description:</strong> Upon successful completion of this course, the student will be able to understand recent advances in natural language processing and apply NLP algorithms and techniques for processing unstructured text. Word-level, syntactic and semantic processing will be considered. Specific topics include rule-based and statistical methods for creating computer programs that analyze, generate and understand human language. Regular expressions and automata, context-free grammars, probabilistic classifiers and machine learning. Applications to real-world problems such as spell-checking, Web search, automatic question answering, authorship identification and developing conversational interfaces.</p>
</section>
<section id="cmsc-525---introduction-to-software-analysis-testing-and-verification" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-525---introduction-to-software-analysis-testing-and-verification">CMSC&nbsp;525 - Introduction to Software Analysis, Testing and Verification</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;401&nbsp;and&nbsp;403. Enrollment is restricted to students with graduate standing or those accepted into the accelerated BS to MS program in computer science.</p>
<p><strong>Description:</strong> An introduction to concepts and techniques used in the analysis of software for certain properties. Using analytic results to derive test data and verify the correct implementation of programs. Flow graphs, fault/failure model, theoretical and practical limitations. Control flow, data flow and error flow analyses. Testing strategies including random, structural, mutation and error flow. Software metrics.</p>
</section>
<section id="cmsc-526---theory-of-programming-languages" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-526---theory-of-programming-languages">CMSC&nbsp;526 - Theory of Programming Languages</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;403, graduate student standing or acceptance into the five-year accelerated BS and MS program in computer science.</p>
<p><strong>Description:</strong> An introduction to the formal semantics of programming languages, logic programming and functional programming. Topics include denotational semantics, attribute grammars, Backus Formal Functional Programming, fixed point semantics, model-theoretic semantics and PROLOG.</p>
</section>
<section id="cmsc-531---3d-computer-vision-for-robot-navigation" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-531---3d-computer-vision-for-robot-navigation">CMSC&nbsp;531 - 3D Computer Vision for Robot Navigation</h2>
<p><strong>Restrictions:</strong> Enrollment is restricted to graduate students in computer science or related discipline or to students accepted into the five-year accelerated program in computer science.</p>
<p><strong>Description:</strong> The course focuses on recent advancements in 3D robotic vision. It covers basic concepts and computational models of 3D sensing, robotic mapping, visual odometry, simultaneous localization and mapping, as well as 3D point data processing for robotic navigation. Students will acquire in-depth knowledge in robotic vision by completing a course project.</p>
</section>
<section id="cmsc-591---topics-in-computer-science" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-591---topics-in-computer-science">CMSC&nbsp;591 - Topics in Computer Science</h2>
<p><strong>Restrictions:</strong> (none)</p>
<p><strong>Description:</strong> May be repeated for credit. Enrollment requires permission of the instructor. The course is open to students with graduate standing or those accepted into the accelerated BS to MS program in computer science. A study of selected topic(s) in computer science at the graduate level. See the Schedule of Classes for specific topics to be offered each semester.</p>
</section>
<section id="cmsc-601---convex-optimization" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-601---convex-optimization">CMSC&nbsp;601 - Convex Optimization</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;501&nbsp;or permission of instructor. Enrollment restricted to students with graduate standing in computer science or related discipline.</p>
<p><strong>Description:</strong> A background in undergraduate-level linear algebra is assumed. Convex sets and functions. Convex optimization problems: Linear, quadratic, semi-definite and cone programs. Duality theory. Approximation algorithms for NP-complete integer optimization problems via semi-definite relaxations and rounding schemes. Algorithms for optimization, such as gradient descent, proximal descent, alternating directions method of multipliers, interior point methods.</p>
</section>
<section id="cmsc-602---operating-systems" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-602---operating-systems">CMSC&nbsp;602 - Operating Systems</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;502.</p>
<p><strong>Description:</strong> A study of operating systems including those in multiprocessor and distributed environments. I/O programming, resource management (including processor and memory management), security and system performance evaluation.</p>
</section>
<section id="cmsc-603---high-performance-distributed-systems" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-603---high-performance-distributed-systems">CMSC&nbsp;603 - High Performance Distributed Systems</h2>
<p><strong>Restrictions:</strong> Enrollment is restricted to students with graduate standing in computer science or related discipline or those accepted into the accelerated BS to MS program in computer science.</p>
<p><strong>Description:</strong> The course will assume undergraduate-level background in algorithms, data structures and parallel programming. Upon successful completion of this course, the student will be able to understand the concepts underlying distributed systems; analyze problems to identify performance bottlenecks, parallelization opportunities and concurrency issues in a distributed environment; create distributed and scalable implementations using multiple hosts/GPUs; design and implement algorithms using Hadoop, Spark and CUDA.</p>
</section>
<section id="cmsc-605---advanced-computer-architecture" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-605---advanced-computer-architecture">CMSC&nbsp;605 - Advanced Computer Architecture</h2>
<p><strong>Restrictions:</strong> EGRE&nbsp;426&nbsp;or with permission of instructor.</p>
<p><strong>Description:</strong> This course will focus on the design and analysis of high performance computer architectures. Topics investigated include pipeline design, superscalar computers, multiprocessors, memory systems, peripherals, interfacing techniques, networks, performance and software issues. Crosslisted as:&nbsp;EGRE&nbsp;635.</p>
</section>
<section id="cmsc-608---advanced-database" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-608---advanced-database">CMSC&nbsp;608 - Advanced Database</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;508.</p>
<p><strong>Description:</strong> Topics discussed include: handling of missing information; the relationship between relational calculus, relational algebra and SQL; logic databases; distributed databases; outer joins; and transaction processing. Emphasis is placed on theoretical issues involved in these topics. In addition students will work in teams to develop a working database application.</p>
</section>
<section id="cmsc-610---algorithmic-foundations-of-bioinformatics" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-610---algorithmic-foundations-of-bioinformatics">CMSC&nbsp;610 - Algorithmic Foundations of Bioinformatics</h2>
<p><strong>Restrictions:</strong> Graduate student standing or acceptance into five-year accelerated program in computer science or related discipline such as bioinformatics.</p>
<p><strong>Description:</strong> The purpose of the course is to teach algorithms for analyzing biological and medical data. The focus will be on understanding the inner workings of algorithms used in bioinformatics tools. Topic covered will include algorithms for assembling and searching biological sequences, finding patterns associated with disease, and exploring biological networks.</p>
</section>
<section id="cmsc-611---computer-multimedia" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-611---computer-multimedia">CMSC&nbsp;611 - Computer Multimedia</h2>
<p><strong>Restrictions:</strong> permission of instructor.</p>
<p><strong>Description:</strong> Study of computer multimedia techniques relating to images, sound, video and text. Emphasis on compression techniques and standard storage formats. This course is programming-intensive.</p>
</section>
<section id="cmsc-612---game-theory-and-security" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-612---game-theory-and-security">CMSC&nbsp;612 - Game Theory and Security</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;401. Enrollment is restricted to students with graduate standing in computer science or those accepted into the accelerated BS to MS program in computer science.</p>
<p><strong>Description:</strong> The course will provide an introduction to game theory and mechanism design concepts. Lectures cover topics such as introduction of games, equilibrium concepts, computation of game-theoretic solution concepts, mechanism, and issues in game theory and mechanism design.</p>
</section>
<section id="cmsc-615---cryptocurrency-and-blockchain-techniques" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-615---cryptocurrency-and-blockchain-techniques">CMSC&nbsp;615 - Cryptocurrency and Blockchain Techniques</h2>
<p><strong>Restrictions:</strong> Enrollment is restricted to students with graduate standing in computer science or a related discipline.</p>
<p><strong>Description:</strong> The course will assume undergraduate-level background in algorithms, data structures and programming. Upon successful completion of this course, the student will be able to understand the major concepts about cryptocurrency and blockchain techniques; be familiar with major blockchain applications as well as real-world issues; understand the underlying consensus mechanisms in the Bitcoin system and other alternative cryptocurrency systems; analyze the security of Nakamoto consensus; understand, write and execute smart contracts using an Ethereum-like platform.</p>
</section>
<section id="cmsc-618---database-and-application-security" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-618---database-and-application-security">CMSC&nbsp;618 - Database and Application Security</h2>
<p><strong>Restrictions:</strong> (none)</p>
<p><strong>Description:</strong> Theory and practice of database and software security focusing in particular on some common database software security risks and on the identification of potential threats and vulnerabilities. Crosslisted as:&nbsp;CISS&nbsp;618.</p>
</section>
<section id="cmsc-619---the-design-and-specifications-of-user-interfaces" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-619---the-design-and-specifications-of-user-interfaces">CMSC&nbsp;619 - The Design and Specifications of User Interfaces</h2>
<p><strong>Restrictions:</strong> Graduate standing and permission of instructor.</p>
<p><strong>Description:</strong> Requires knowledge of first order predicate calculus and context-free languages. Focuses on human-computer interface design principles and methodology and formal specifications of user interfaces.</p>
</section>
<section id="cmsc-620---applied-cryptography" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-620---applied-cryptography">CMSC&nbsp;620 - Applied Cryptography</h2>
<p><strong>Restrictions:</strong> (none)</p>
<p><strong>Description:</strong> Provides a comprehensive survey of modern cryptography. Included are techniques of enciphering and deciphering messages using cryptographic algorithms, block ciphers and block cipher modes, hash functions and message authentication codes, public key cryptography and digital signatures, and steganography. Crosslisted as:&nbsp;CISS&nbsp;624.</p>
</section>
<section id="cmsc-621---theory-of-computation" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-621---theory-of-computation">CMSC&nbsp;621 - Theory of Computation</h2>
<p><strong>Restrictions:</strong> graduate student standing and permission of instructor.</p>
<p><strong>Description:</strong> Discussion of the complexity and computability of problems and programs. Topics will include unsolvability, universal programs and abstract complexity.</p>
</section>
<section id="cmsc-622---network-and-system-security" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-622---network-and-system-security">CMSC&nbsp;622 - Network and System Security</h2>
<p><strong>Restrictions:</strong> (none)</p>
<p><strong>Description:</strong> Studies the principles of network security and system security. Included are topics relating to application layer security, TCP layer security, network layer security and link layer security and the use of access control, intrusion detection, intrusion prevention and other related tools.</p>
</section>
<section id="cmsc-623---cloud-computing" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-623---cloud-computing">CMSC&nbsp;623 - Cloud Computing</h2>
<p><strong>Restrictions:</strong> (none)</p>
<p><strong>Description:</strong> Provides an introduction to cloud computing architecture and cloud computing security. The course covers the basic concepts of cloud computing, including memory virtualization, device virtualization and related security problems in cloud computing.</p>
</section>
<section id="cmsc-624---software-quality-assurance" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-624---software-quality-assurance">CMSC&nbsp;624 - Software Quality Assurance</h2>
<p><strong>Restrictions:</strong> a course in software engineering and graduate standing in computer science, or permission of instructor.</p>
<p><strong>Description:</strong> A study of issues that affect the quality of software and of methodology to assure that software products are of the desired quality. This also includes issues in assessing product quality as well as the process by which the software is produced. Topics include various methodologies, standards, metrics and tools.</p>
</section>
<section id="cmsc-625---advanced-software-analysis-testing-and-verification" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-625---advanced-software-analysis-testing-and-verification">CMSC&nbsp;625 - Advanced Software Analysis, Testing and Verification</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;525.</p>
<p><strong>Description:</strong> Studies the concepts and techniques used in the analysis of software and the derivation of test data. Focuses on software metrics and reliability; construction of tools to aid software analysis and testing. Requires students to review seminal and current papers from the literature, and lead their discussion in class.</p>
</section>
<section id="cmsc-628---mobile-networks-applications-modeling-and-analysis" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-628---mobile-networks-applications-modeling-and-analysis">CMSC&nbsp;628 - Mobile Networks: Applications, Modeling and Analysis</h2>
<p><strong>Restrictions:</strong> Enrollment is restricted to students with graduate standing in computer science or a related discipline.</p>
<p><strong>Description:</strong> The course will assume undergraduate-level background in algorithms, data structures, programming and networks. Upon successful completion of this course, the student will be able to understand the major concepts about mobile networks such as device-to-device communication technologies, mobility models and coverage; be familiar with various mobile network types (e.g., mobile social networks, delay tolerant networks, overlay networks, vehicular networks and cellular networks) and devices (e.g., smartphones, femtocells, WiFi), learn how to model mobile networks with stochastic processes and real datasets; be able to use different networking simulators; and understand various routing algorithms and analyze their behavior.</p>
</section>
<section id="cmsc-630---image-analysis" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-630---image-analysis">CMSC&nbsp;630 - Image Analysis</h2>
<p><strong>Restrictions:</strong> Enrollment is restricted to students with graduate standing in engineering or science or by permission of the instructor.</p>
<p><strong>Description:</strong> Introduces theoretical and practical aspects of computer vision for image processing and understanding. It provides a comprehensive walkthrough from basics of image preparation to using computational intelligence tools for knowledge discovery from images. The course will cover basics of image processing and computer vision, including image sampling and quantization, color, pixel-based operations, image filtering, morphological image processing, and image transforms; information extraction including segmentation and feature extraction; pattern recognition for computer vision: classification, novelty and object detection, image understanding, learning from video streams, and tensor-based methods. Examples will include medical image analysis, object recognition in ground and aerial photographs and hyperspectral imaging.</p>
</section>
<section id="cmsc-635---knowledge-discovery-and-data-mining" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-635---knowledge-discovery-and-data-mining">CMSC&nbsp;635 - Knowledge Discovery and Data Mining</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;401&nbsp;or corequisite:&nbsp;CMSC&nbsp;501. Enrollment is restricted to students with graduate standing in computer science or a related discipline such as bioinformatics, or those accepted into the accelerated BS to MS program in computer science.</p>
<p><strong>Description:</strong> Covers knowledge discovery and data mining concepts, tools and methods; provides hands-on experience based on a project involving analysis of large real-life data. Topics include the knowledge discovery process, data storage and representation, preprocessing algorithms for missing data imputation, feature selection and discretization; unsupervised learning algorithms for clustering and association mining; supervised learning algorithms including decision trees, Bayesian models and introduction to support vector machines and neural networks; ensemble learning; protocols and measures for validation of predictive models; and data security and privacy issues.</p>
</section>
<section id="cmsc-636---artificial-neural-networks-and-deep-learning" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-636---artificial-neural-networks-and-deep-learning">CMSC&nbsp;636 - Artificial Neural Networks and Deep Learning</h2>
<p><strong>Restrictions:</strong> Enrollment is restricted to students with graduate standing in computer science.</p>
<p><strong>Description:</strong> The course will assume undergraduate-level background in programming, algorithms, linear algebra, calculus, statistics and probability. Topics ranging from fundamental learning rules, functional, cascade correlational, recurrent and gradient descent networks, to neocognitron, softmax, deep convolutional networks, autoencoders and pretrained deep learning (restricted Boltzmann machines). Students will be required to work in teams on a class paper.</p>
</section>
<section id="cmsc-654---memory-and-malware-forensics" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-654---memory-and-malware-forensics">CMSC&nbsp;654 - Memory and Malware Forensics</h2>
<p><strong>Restrictions:</strong> CMSC&nbsp;312. Enrollment is restricted to students with graduate standing in computer science or a related discipline, or those accepted into the accelerated BS to MS program in computer science.</p>
<p><strong>Description:</strong> Students should have significant programming experience. This course provides foundation for memory and malware forensics, using the Volatility memory forensics framework, an open source toolkit written in Python. It is focused on investigation of the contents of volatile computer memory (RAM), to reveal hidden malware processes, network connections, clipboard contents, evidence of malware and other malicious evidence. The course will teach skills for analyzing internals of operating systems, such as Mac, Windows and Linux, by concentrating on data structures used by these operating systems.</p>
</section>
<section id="cmsc-678---statistical-learning-and-fuzzy-logic-algorithms" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-678---statistical-learning-and-fuzzy-logic-algorithms">CMSC&nbsp;678 - Statistical Learning and Fuzzy Logic Algorithms</h2>
<p><strong>Restrictions:</strong> MATH/STAT&nbsp;309&nbsp;or&nbsp;MATH&nbsp;310.</p>
<p><strong>Description:</strong> The course considers two central problems in modern science and engineering: i) the problem of statistical learning from examples (empirical data) and ii) the problem of embedding existing human knowledge into workable mathematics. Topics include: examples of multivariate functional mapping, basics of classic classification and regression, support vector machines as a learning paradigm based on structural risk minimization, fuzzy logic algorithms, basics of multi-class classification over high dimensional spaces, curve and surface fittings, multivariate function approximation and nonlinear optimization; fuzzy logic systems; crisp and fuzzy sets, linguistic variables, fuzzy set theory; if-then rules, fuzzy interference, fuzzification and defuzzification, neuro-fuzzy paradigms.</p>
</section>
<section id="cmsc-691---special-topics-in-computer-science" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-691---special-topics-in-computer-science">CMSC&nbsp;691 - Special Topics in Computer Science</h2>
<p><strong>Restrictions:</strong> at least one graduate-level computer science course pertaining to the topic area and permission of instructor.</p>
<p><strong>Description:</strong> An advanced study of selected topic(s) in computer science at the graduate level. See the Schedule of Classes for specific topics to be offered each semester.</p>
</section>
<section id="cmsc-692---independent-study" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-692---independent-study">CMSC&nbsp;692 - Independent Study</h2>
<p><strong>Restrictions:</strong> Enrollment restricted to students with graduate standing and consent of instructor.</p>
<p><strong>Description:</strong> Independent study done under the supervision of a faculty member. The student must identify a faculty member willing to supervise the research and submit a proposal for approval by the computer science graduate committee no later than the 10th week of the prior semester. A written report and an oral presentation are required upon completion of the research project. Graded as Pass/Fail.</p>
</section>
<section id="cmsc-697---directed-research" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-697---directed-research">CMSC&nbsp;697 - Directed Research</h2>
<p><strong>Restrictions:</strong> (none)</p>
<p><strong>Description:</strong> May be repeated for credit. A total of three credits may be used to fulfill the MS in Computer Science thesis requirement. Independent research culminating in the writing of the required thesis or dissertation. The student must identify a faculty member willing to supervise the research and submit a proposal to the computer science graduate committee no later than the 10th week of the prior semester. This proposal must be approved before the student can register for the course. Graded as S/U/F.</p>
</section>
<section id="cmsc-701---research-methods" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-701---research-methods">CMSC&nbsp;701 - Research Methods</h2>
<p><strong>Restrictions:</strong> PHD standing or permission of instructor.</p>
<p><strong>Description:</strong> Covers the principles of conducting a research project, reporting the findings in the form of a journal paper and promoting the research through public presentations. Students learn to write grant proposals and practice reviewing research papers and grant proposals. The main emphasis of the course is writing a paper and a grant proposal in a format compliant with NSF, NIH or DoD guidelines.</p>
</section>
<section id="cmsc-702---computer-science-seminar" class="level2">
<h2 class="anchored" data-anchor-id="cmsc-702---computer-science-seminar">CMSC&nbsp;702 - Computer Science Seminar</h2>
<p><strong>Restrictions:</strong> Enrollment restricted to students in the doctoral program in computer science. Students will attend a week</p>
<p><strong>Description:</strong> Students will attend a weekly research seminar in which the topic and speaker will change each week in order to cover a broad range of subjects at the forefront of computer science research. Students will have to present and to write a report on at least one seminar presented by other speakers. The objective is to expose students to research topics and scholars in the field of computer science as well as to provide them experience in delivering and critiquing seminar talks. Graded as satisfactory/unsatisfactory.</p>
</section>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>