---
semester: "Spring 2023"
course-prefix-and-number: "CMSC 475"
course-title: "Design and Implementation of User Interfaces"
meeting-days-and-times: "MWF 11am-12pm"
meeting-location: "East Hall 2214"
instructor-name: "Dr. John Leonard"
instructor-title: "Professor"
instructor-email: "jdleonard@vcu.edu"
instructor-office-hours: "Mon 8am-9am; Tue 8am-9am"
instructor-office-location: "ERB 2327"
course-description: "(course description here)"

course-canvas-url:
course-discord-url:
course-gradescope-url:

title: "{{< meta course-title  >}}"
subtitle: "{{< meta semester >}}, {{< meta meeting-days-and-times >}}, {{< meta meeting-location >}}"

---

## Course catalog description

Semester course; 3 lecture hours. 3 credits. Prerequisite: CMSC 355 with a minimum grade of C. Enrollment is restricted to majors in the computer science program. This course investigates the design and implementation of user interfaces and the evaluation of user experiences. Particular emphasis is placed on creating professional-quality designs and implementations and on evaluating these implementations with end-users. Students will create their own UIs as well as critique others to develop a deep understanding of what works in practice.

## Instructor’s Course Description

At completion of the course students will be able to design and implement user interfaces appropriate to the design need following best UI practices. Students will build wireframes, prototypes, working models, and evaluate their designs. Students will be evaluated on their submissions and on their participation in classroom activities.

## Instructor and course links

{{< meta instructor-name >}}, {{< meta instructor-title >}}, [{{< meta instructor-email >}}](mailto:{{< meta instructor-email >}}), Office: {{< meta instructor-office-location >}}

Canvas “announcements” will be used to send out official emails regarding updates and changes to the syllabus, course outline, and course projects. Regularly check the course Canvas and watch your email for changes.

GradeScope will be used for most homework submissions and grading. You should know how to create PDF documents and post PDF documents to Gradescope. You should know how to use Github, as many homework assignments will require submission of material to Gradescope using a Github repository.

Discord is the unofficial communications platform for the course. Join the discord and then change your server name to your preferred/real name associated with the course roster.

This is a face-to-face course. In class participation is an important part of learning this material and will score points towards your final grade. However, recognizing that life happens I will work to stream the lectures live and record the lectures using Zoom. Recordings will be posted to the course Canvas.

## Contact information

If you have course related questions, I HIGHLY PREFER that you use the course discord. I regularly monitor discord. You’ll get the added benefit that other students in the class may be able to get your question answered faster. Please do not DM (direct message) me in discord, I cannot guarantee that I will respond. (I also can’t tell who you are!)

If you need to contact me directly USE EMAIL. My goal is to respond to your email within 24 hours or much less. If I will be unavailable for a longer stretch of time, I will let the class know in an announcement.

## ABET Student Learning Outcomes
- Analyze a complex computing problem and to apply principles of computing and other relevant disciplines to identify solutions.

- Design, implement, and evaluate a computing-based solution to meet a given set of computing requirements in the context of the program’s discipline.

- Communicate effectively in a variety of professional contexts.

- Function effectively as a member or leader of a team engaged in activities appropriate to the program’s discipline.

- Apply computer science theory and software development fundamentals to produce computing-based solutions.

- Software Engineering: Apply software engineering techniques to implement practical solutions within the context of a larger team in a timely, organized, and professional manner


## Course Structure

Follow the course schedule, watch the assigned videos, review the assigned readings prior to class, and perform any other activities prior to each class period.

This course will require active participation and collaboration with fellow classmates. Be prepared to complete assignments as well as participate in group discussions on topics related to the assigned readings.

Class materials will be available from the course Canvas.

Assignments and projects will be submitted online.

## Online Learning Considerations

Some elements of the course may require remote participation in classroom activities. When learning remotely it is important to keep up with the class content (readings & videos) as well as the discussion and assignments. Check the course schedule regularly to familiarize yourself with the work and due dates.


## Final Exam Date and time

## Course assessment and grading policy 

Throughout the semester you will submit in-class exercises and outside-of-class assignments. When working in groups each member of the group will receive the same score unless otherwise noted. See the course outline for a tentative list of assignments and due dates.

@tbl-panel below highlights how grades are assigned and the weights associated with the different course deliverables.

::: {#tbl-panel layout-ncol=2}

| Score range | Grade |
|:-----------:|:-----:|
| 90<= X      |   A   |
| 80<= X < 90 |   B   |
| 70<= X < 80 |   C   |
| 60<= X < 70 |   D   |
|  X < 60     |   F   |

: Grading scale {#tbl-left}

| Deliverable |  %  |
|-------------|:---:|
| Projects    | 50% |
| In-class    | 30% |
| Midterm     | 10% |
| Final       | 10% |

: Grade weights {#tbl-right}

Course grading scheme

:::

## Technology considerations

This is a course in computer science. This course builds on knowledge, skills, and abilities you have acquired in previous classes. Bring your laptop to class and be prepared to use a browser, a text/code editor, and other general purpose computing tools. All the standard VCU technology guidelines and College of Engineering technology guidelines apply.

## University Resources

Use VCU Libraries to find and access library resources, spaces, technology and services that support and enhance all learning opportunities at the university. See: <https://www.library.vcu.edu/>

## Institutional Policies

Students should visit <http://go.vcu.edu/syllabus> and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

### Accommodations for Students with Disabilities

Disability Statement: If you are a student with a disability requesting reasonable accommodations in this course, please visit Student Accessibility and Educational Opportunity. All requests for reasonable accommodations require registration with SAEO in advance of need. Faculty, students and SAEO will work together regarding classroom accommodations. You are encouraged to discuss approved accommodations with your faculty. 

### Counseling Services

Resources for online students can be found through the Online Counseling Center.

### Tutoring
The Campus Learning Center offers appointment, drop-in and group tutoring in undergraduate courses across the disciplines.
Writing Center
The writing center provides assistance at all stages of the writing process, from brainstorming to final draft.
Cheating and Plagiarism
Plagiarism is stealing and passing off the ideas or words of another as one’s own; it is using another’s production without crediting the source. The best way to avoid plagiarism is to cite properly in any assignment information and concepts that are not your own originally. If a student is discovered to have plagiarized, that student will fail that particular assignment.
Academic integrity is expected in all aspects at the university including this course. Don’t expect less of yourself than you do of your students For more information: <https://students.vcu.edu/studentconduct/>

## Course Policies

### Late/Missing Work Policy
Late work will sometimes be accepted on an assignment-by-assignment basis. Please review the course calendar to ensure you are aware of all due dates and that you plan accordingly. All due dates are in Eastern Standard Time. If you have a reason for an extended absence from your academic studies, such as hospitalization or incarceration, please contact me.

### Group assignments and collaboration

Please read the assignments to determine whether they are to be completed individually or in teams. I appreciate and promote collaboration between students on ALL activities. It’s good to share ideas and strategies. New and different experiences and perspectives will help you grow and expand your own perspectives.

Individual assignments often require internal reflection, writing and coding. For individual assignments, I expect you to create your own code (not cut and paste from friend) and present YOUR OWN ideas as part of the submission. I’ll be providing feedback on your ideas.

Group assignments often require brainstorming, strategizing and problem solving, and debating.  For group assignments I expect everyone on the team to participate in one role or another.

Ultimately, YOU are responsible for your own learning. I can guide you and your classmates can contribute to your learning, but in the end, the responsibility and the grade are yours alone.

### Accessibility Concerns

I will do all I can to accommodate any special learning needs. I welcome your feedback and suggestions. As noted earlier, if you require formal accommodations, please coordinate with the 

Student Accessibility and Educational Opportunity Office:
(https://saeo.vcu.edu/getting-started/who-we-serve/)

### Intellectual Property and Copyright

Intellectual property and copyrighted material that is presented in this course is not for redistribution.

## VCU Syllabus Statement
Students should visit <http://go.vcu.edu/syllabus> and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

## VCU Important dates
Important dates for the current and future semesters are listed in the [VCU Academic Calendar](https://academiccalendars.vcu.edu/).

