project:
  type: website
  output-dir: ..\..\docs

website:
  title: "VCU Computer Science Courses"
  search:
    location: navbar
    type: overlay
  navbar:
    background: primary
    search: true
    right: #changed nav menu items to align to the right
      - text: "Home"
        file: index.qmd
      - text: "Catalog"
        file: catalog.qmd
      - text: "Syllabii"
        file: syllabii.qmd
      - text: "Topics"
        file: topics.qmd
      - text: "Coverage"
        file: coverage.qmd
      - text: "Outcomes"
        file: outcomes.qmd
      - text: "Bulletin"
        file: bulletin.qmd
      - text: "Code"
        file: scanner.md
    logo: assets/CS-icon-01.png #vcu computer science emblem 
    logo-href: /index.html
  sidebar:
    style: "docked"
    search: false
    collapse-level: 1
    contents:
    - _contents.yml

format:
  html:
    theme: quarto_vcutheme.scss
    mainfont: 'Roboto' #vcu's body text font.
    toc: true
    html-math-method: katex

metadata-files:
  - _contents.yml
