project:
  type: website
  output-dir: ..\..\docs

website:
  title: "CMSC Courses"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Listing"
        file: listing.qmd
  sidebar:
    style: "floating"
    search: false
    collapse-level: 1
    contents:
    - _contents.yml

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    html-math-method: katex

metadata-files:
  - _contents.yml
