project:
  type: website
  output-dir: ..\..\docs

website:
  title: "CMSC Courses"
  search: true
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Courses"
        file: listing.qmd
      - text: "Topics"
        file: topics.qmd
      - text: "Code"
        file: scanner.md
  sidebar:
    style: "docked"
    search: false
    collapse-level: 1
    contents:
    - _contents.yml

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    html-math-method: katex

metadata-files:
  - _contents.yml
