---
title: "CMSC 440 - Data Communication and Networking"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; 3 lecture hours. 3 credits. Prerequisite: CMSC 257 with a minimum grade of C. Enrollment is restricted to majors in the College of Engineering. This course explores computer networking, focusing on the applications and protocols that run on the Internet. Students will take a top-down approach to the layered network architecture, studying applications first and then proceeding down the network “stack” toward the physical link. Students will examine the operation of applications such as the web, FTP, e-mail and DNS. At the transport layer, students will study both connectionless UDP and connection-oriented TCP, with an in-depth study of TCP operation, specifically flow control and congestion control. Data communications are explored through various data routing protocols. Additional topics include network security and wireless/mobile networking.


## Restrictions including pre- or co-requisities
 
CMSC 257 with a minimum grade of C. Enrollment is restricted to majors in the College of Engineering.

## Description

This course explores computer networking, focusing on the applications and protocols that run on the Internet. Students will take a top-down approach to the layered network architecture, studying applications first and then proceeding down the network “stack” toward the physical link. Students will examine the operation of applications such as the web, FTP, e-mail and DNS. At the transport layer, students will study both connectionless UDP and connection-oriented TCP, with an in-depth study of TCP operation, specifically flow control and congestion control. Data communications are explored through various data routing protocols. Additional topics include network security and wireless/mobile networking.

## Past Syllabii

<a href='./202120/CMSC_440_Syllabus_Spring_2021.pdf'>Spring 2021</a>, <a href='./202220/CMSC_440_Syllabus_Spring_2022.pdf'>Spring 2022</a>, <a href='./202310/CMSC_440_Syllabus_Fall_2022.pdf'>Fall 2022</a>, <a href='./202320/CMSC_440_Syllabus_Spring_2023.pdf'>Spring 2023</a>

## Topics

architecture, client-server model, computer networks, data, dns, dns , e-mail, flow control, http application, internet, mail applications, network edge, network models, networks, networks vulnerability, pipelining, protocol layers, reliable transmission, socket programming, tcp, udp, web development

## ABET Coverage

computer architecture and organization, networking and communication, information management, concepts of programming languages, techniques, skills, and tools

## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage                           Adjusted Topic          Course
--------------------------------------  ----------------------  ----------------------------------
computer architecture and organization  architecture            <a href='CMSC440.qmd'>CMSC 440</a>
concepts of programming languages       flow control            <a href='CMSC440.qmd'>CMSC 440</a>
information management                  data                    <a href='CMSC440.qmd'>CMSC 440</a>
networking and communication            client-server model     <a href='CMSC440.qmd'>CMSC 440</a>
networking and communication            computer networks       <a href='CMSC440.qmd'>CMSC 440</a>
networking and communication            dns                     <a href='CMSC440.qmd'>CMSC 440</a>
networking and communication            dns                     <a href='CMSC440.qmd'>CMSC 440</a>
networking and communication            e-mail                  <a href='CMSC440.qmd'>CMSC 440</a>
networking and communication            internet                <a href='CMSC440.qmd'>CMSC 440</a>
networking and communication            mail applications       <a href='CMSC440.qmd'>CMSC 440</a>
networking and communication            network edge            <a href='CMSC440.qmd'>CMSC 440</a>
networking and communication            network models          <a href='CMSC440.qmd'>CMSC 440</a>
networking and communication            networks                <a href='CMSC440.qmd'>CMSC 440</a>
networking and communication            networks vulnerability  <a href='CMSC440.qmd'>CMSC 440</a>
networking and communication            pipelining              <a href='CMSC440.qmd'>CMSC 440</a>
networking and communication            protocol layers         <a href='CMSC440.qmd'>CMSC 440</a>
networking and communication            reliable transmission   <a href='CMSC440.qmd'>CMSC 440</a>
networking and communication            socket programming      <a href='CMSC440.qmd'>CMSC 440</a>
networking and communication            tcp                     <a href='CMSC440.qmd'>CMSC 440</a>
networking and communication            udp                     <a href='CMSC440.qmd'>CMSC 440</a>
networking and communication            web development         <a href='CMSC440.qmd'>CMSC 440</a>
techniques, skills, and tools           http application        <a href='CMSC440.qmd'>CMSC 440</a>


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


