---
title: "CMSC 320 - Software Engineering and Web Development"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; 3 lecture hours (delivered online). 3 credits. Prerequisite: CMSC 210. Introduction to software engineering and web development. The course introduces students to the software development process, including design, development and testing principles. Students will apply these principles in the development of a web application. This course is not applicable for credit toward any College of Engineering degrees.


## Restrictions including pre- or co-requisities
 
CMSC 210.

## Description

Introduction to software engineering and web development. The course introduces students to the software development process, including design, development and testing principles. Students will apply these principles in the development of a web application. This course is not applicable for credit toward any College of Engineering degrees.

## Past Syllabii

<a href='./202120/CMSC_320_Syllabus_Spring_2021.pdf'>Spring 2021</a>, <a href='./202210/CMSC_320_Syllabus_Fall_2021.pdf'>Fall 2021</a>, <a href='./202220/CMSC_320_Syllabus_Spring_2022.pdf'>Spring 2022</a>, <a href='./202310/CMSC_320_Syllabus_Fall_2022.pdf'>Fall 2022</a>, <a href='./202320/CMSC_320_Syllabus_Spring_2023.pdf'>Spring 2023</a>

## Topics

design, development, documentation, gathering, software development, systems development, testing, testing functionality, web development

## ABET Coverage

techniques, skills, and tools, software development, concepts of programming languages

## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage                      Adjusted Topic         Course
---------------------------------  ---------------------  ----------------------------------
concepts of programming languages  testing                <a href='CMSC320.qmd'>CMSC 320</a>
concepts of programming languages  testing functionality  <a href='CMSC320.qmd'>CMSC 320</a>
software development               development            <a href='CMSC320.qmd'>CMSC 320</a>
software development               software development   <a href='CMSC320.qmd'>CMSC 320</a>
software development               systems development    <a href='CMSC320.qmd'>CMSC 320</a>
software development               web development        <a href='CMSC320.qmd'>CMSC 320</a>
techniques, skills, and tools      design                 <a href='CMSC320.qmd'>CMSC 320</a>
techniques, skills, and tools      documentation          <a href='CMSC320.qmd'>CMSC 320</a>
techniques, skills, and tools      gathering              <a href='CMSC320.qmd'>CMSC 320</a>


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


