---
title: "CMSC 611 - Computer Multimedia"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; 3 lecture hours. 3 credits. Prerequisite: permission of instructor. Study of computer multimedia techniques relating to images, sound, video and text. Emphasis on compression techniques and standard storage formats. This course is programming-intensive.


## Restrictions including pre- or co-requisities
 
permission of instructor.

## Description

Study of computer multimedia techniques relating to images, sound, video and text. Emphasis on compression techniques and standard storage formats. This course is programming-intensive.

## Past Syllabii

(none since Spring 2021)

## Topics

compression, multimedia , storage formats

## ABET Coverage

concepts of programming languages, information management

## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage                      Adjusted Topic    Course
---------------------------------  ----------------  ----------------------------------
concepts of programming languages  compression       <a href='CMSC611.qmd'>CMSC 611</a>
concepts of programming languages  multimedia        <a href='CMSC611.qmd'>CMSC 611</a>
information management             storage formats   <a href='CMSC611.qmd'>CMSC 611</a>


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


