---
title: "CMSC 403 - Programming Languages"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; 3 lecture hours. 3 credits. Prerequisites: CMSC 256 and CMSC 303, both with a minimum grade of C. Survey of representative modern programming languages. Formal definition of programming languages including specifications of syntax and semantics. Precedence, infix, prefix and postfix notation. Global properties of algorithmic languages. Sub-routines, co-routines and tasks. List processing, string manipulation, data description and simulation languages. Run-time representation of program and data structures.


## Restrictions including pre- or co-requisities
 
CMSC 256 and CMSC 303, both with a minimum grade of C.

## Description

Survey of representative modern programming languages. Formal definition of programming languages including specifications of syntax and semantics. Precedence, infix, prefix and postfix notation. Global properties of algorithmic languages. Sub-routines, co-routines and tasks. List processing, string manipulation, data description and simulation languages. Run-time representation of program and data structures.

## Past Syllabii

<a href='./202120/CMSC_403_Syllabus_Spring_2021.pdf'>Spring 2021</a>, <a href='./202210/CMSC_403_Syllabus_Fall_2021.pdf'>Fall 2021</a>, <a href='./202220/CMSC_403_Syllabus_Spring_2022.pdf'>Spring 2022</a>, <a href='./202310/CMSC_403_Syllabus_Fall_2022.pdf'>Fall 2022</a>, <a href='./202320/CMSC_403_Syllabus_Spring_2023.pdf'>Spring 2023</a>

## Topics

algorithms, co-routines, data, data structures, design, functional programming, infix, languages, lists, object oriented programming, parsing, postfix, precendence, prefix, semantics, strings, sub-routines, symbol table, syntax

## ABET Coverage

algorithms and complexity, concepts of programming languages, information management, general purpose programming language, techniques, skills, and tools

## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage                         Adjusted Topic               Course
------------------------------------  ---------------------------  ----------------------------------
algorithms and complexity             algorithms                   <a href='CMSC403.qmd'>CMSC 403</a>
concepts of programming languages     co-routines                  <a href='CMSC403.qmd'>CMSC 403</a>
concepts of programming languages     design                       <a href='CMSC403.qmd'>CMSC 403</a>
concepts of programming languages     functional programming       <a href='CMSC403.qmd'>CMSC 403</a>
concepts of programming languages     infix                        <a href='CMSC403.qmd'>CMSC 403</a>
concepts of programming languages     lists                        <a href='CMSC403.qmd'>CMSC 403</a>
concepts of programming languages     parsing                      <a href='CMSC403.qmd'>CMSC 403</a>
concepts of programming languages     precendence                  <a href='CMSC403.qmd'>CMSC 403</a>
concepts of programming languages     prefix                       <a href='CMSC403.qmd'>CMSC 403</a>
concepts of programming languages     semantics                    <a href='CMSC403.qmd'>CMSC 403</a>
concepts of programming languages     strings                      <a href='CMSC403.qmd'>CMSC 403</a>
concepts of programming languages     sub-routines                 <a href='CMSC403.qmd'>CMSC 403</a>
concepts of programming languages     symbol table                 <a href='CMSC403.qmd'>CMSC 403</a>
concepts of programming languages     syntax                       <a href='CMSC403.qmd'>CMSC 403</a>
general purpose programming language  languages                    <a href='CMSC403.qmd'>CMSC 403</a>
general purpose programming language  object oriented programming  <a href='CMSC403.qmd'>CMSC 403</a>
information management                data                         <a href='CMSC403.qmd'>CMSC 403</a>
information management                data structures              <a href='CMSC403.qmd'>CMSC 403</a>
techniques, skills, and tools         postfix                      <a href='CMSC403.qmd'>CMSC 403</a>


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


