---
title: "CMSC 475 - Design and Implementation of User Interfaces"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; 3 lecture hours. 3 credits. Prerequisite: CMSC 355 with a minimum grade of C. Enrollment is restricted to majors in the computer science program. This course investigates the design and implementation of user interfaces and the evaluation of user experiences. Particular emphasis is placed on creating professional-quality designs and implementations and on evaluating these implementations with end-users. Students will create their own UIs as well as critique others to develop a deep understanding of what works in practice.


## Restrictions including pre- or co-requisities
 
CMSC 355 with a minimum grade of C. Enrollment is restricted to majors in the computer science program.

## Description

This course investigates the design and implementation of user interfaces and the evaluation of user experiences. Particular emphasis is placed on creating professional-quality designs and implementations and on evaluating these implementations with end-users. Students will create their own UIs as well as critique others to develop a deep understanding of what works in practice.

## Past Syllabii

<a href='./202120/CMSC_475_Syllabus_Spring_2021.pdf'>Spring 2021</a>, <a href='./202220/CMSC_475_Syllabus_Spring_2022.pdf'>Spring 2022</a>, <a href='./202320/CMSC_475_Syllabus_Spring_2023.pdf'>Spring 2023</a>

## Topics

design, end-users, interfaces, user interface

## ABET Coverage

concepts of programming languages

## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage                      Adjusted Topic    Course
---------------------------------  ----------------  ----------------------------------
concepts of programming languages  design            <a href='CMSC475.qmd'>CMSC 475</a>
concepts of programming languages  end-users         <a href='CMSC475.qmd'>CMSC 475</a>
concepts of programming languages  interfaces        <a href='CMSC475.qmd'>CMSC 475</a>
concepts of programming languages  user interface    <a href='CMSC475.qmd'>CMSC 475</a>


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


