---
title: "CMSC 452 - Senior Project II"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; 1 lecture hour. 1 credit. Prerequisites: CMSC 441, CMSC 451 and CMSC 508, each with a minimum grade of C. Corequisite: CMSC 442. Enrollment is restricted to students with senior standing in the computer science department. This weekly seminar presents and discusses topics relevant to senior-level computer science students in support of the capstone project and upcoming graduation. A single course coordinator manages and administers the course and schedules the various faculty lectures and guest speakers. Topics include, but are not limited to, the following: proposal writing; project planning and management; scheduling resources and budgeting for software development projects; patents and intellectual property; entrepreneurship; ethical, legal and social issues in computing; and professional responsibilities of computer scientists. Each student will write and revise a research paper on a technical topic associated with his or her project or experience. Students must continue on the same project that was started in CMSC 451. A final project report and presentation, which will include a discussion of associated legal, social and/or ethical issues, are due at the conclusion of the two-semester project or experience. The courses in this sequence cannot be counted as upper-level CMSC electives for students graduating under bulletins prior to 2008-09.


## Restrictions including pre- or co-requisities
 
CMSC 441, CMSC 451 and CMSC 508, each with a minimum grade of C. Corequisite: CMSC 442. Enrollment is restricted to students with senior standing in the computer science department.

## Description

This weekly seminar presents and discusses topics relevant to senior-level computer science students in support of the capstone project and upcoming graduation. A single course coordinator manages and administers the course and schedules the various faculty lectures and guest speakers. Topics include, but are not limited to, the following: proposal writing; project planning and management; scheduling resources and budgeting for software development projects; patents and intellectual property; entrepreneurship; ethical, legal and social issues in computing; and professional responsibilities of computer scientists. Each student will write and revise a research paper on a technical topic associated with his or her project or experience. Students must continue on the same project that was started in CMSC 451. 

## Past Syllabii

<a href='./202120/CMSC_452_Syllabus_Spring_2021.pdf'>Spring 2021</a>, <a href='./202220/CMSC_452_Syllabus_Spring_2022.pdf'>Spring 2022</a>, <a href='./202320/CMSC_452_Syllabus_Spring_2023.pdf'>Spring 2023</a>

## Topics

agile, ci/cd, code management, entrepreneurship, final project, maintainability, project planning, scalability, security, social aspects of technology, software development, teamwork, testing

## ABET Coverage

software development, concepts of programming languages, general purpose programming language, security and privacy, local and global impacts

## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage                         Adjusted Topic                Course
------------------------------------  ----------------------------  ----------------------------------
concepts of programming languages     entrepreneurship              <a href='CMSC452.qmd'>CMSC 452</a>
concepts of programming languages     maintainability               <a href='CMSC452.qmd'>CMSC 452</a>
concepts of programming languages     scalability                   <a href='CMSC452.qmd'>CMSC 452</a>
concepts of programming languages     teamwork                      <a href='CMSC452.qmd'>CMSC 452</a>
concepts of programming languages     testing                       <a href='CMSC452.qmd'>CMSC 452</a>
general purpose programming language  final project                 <a href='CMSC452.qmd'>CMSC 452</a>
general purpose programming language  project planning              <a href='CMSC452.qmd'>CMSC 452</a>
local and global impacts              social aspects of technology  <a href='CMSC452.qmd'>CMSC 452</a>
security and privacy                  security                      <a href='CMSC452.qmd'>CMSC 452</a>
software development                  agile                         <a href='CMSC452.qmd'>CMSC 452</a>
software development                  ci/cd                         <a href='CMSC452.qmd'>CMSC 452</a>
software development                  code management               <a href='CMSC452.qmd'>CMSC 452</a>
software development                  software development          <a href='CMSC452.qmd'>CMSC 452</a>


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


