---
title: "CMSC 256 - Data Structures and Object Oriented Programming"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; 3 lecture and 2 laboratory hours. 4 credits. Prerequisite: CMSC 255 with a minimum grade of C; corequisite: CMSC 302. Advanced programming using Java. Topics include introduction to object-oriented design, inheritance, polymorphism, exceptions, interfaces, linked lists, stacks, queues, binary trees, recursion, and basic searching and sorting techniques. Continued focus on program testing and UML notation. Students may not receive credit for both CMSC 256 and INFO 350.


## Restrictions including pre- or co-requisities
 
CMSC 255 with a minimum grade of C; corequisite: CMSC 302.

## Description

Advanced programming using Java. Topics include introduction to object-oriented design, inheritance, polymorphism, exceptions, interfaces, linked lists, stacks, queues, binary trees, recursion, and basic searching and sorting techniques. Continued focus on program testing and UML notation. Students may not receive credit for both CMSC 256 and INFO 350.

## Past Syllabii

<a href='./202120/CMSC_256_Syllabus_Spring_2021.pdf'>Spring 2021</a>, <a href='./202210/CMSC_256_Syllabus_Fall_2021.pdf'>Fall 2021</a>, <a href='./202220/CMSC_256_Syllabus_Spring_2022.pdf'>Spring 2022</a>, <a href='./202310/CMSC_256_Syllabus_Fall_2022.pdf'>Fall 2022</a>, <a href='./202320/CMSC_256_Syllabus_Spring_2023.pdf'>Spring 2023</a>

## Topics

abstract complexity, algorithms, basic searching, binary trees, classes, data structures, deques, exceptions, generics, graphs, hash functions, inheritance, interfaces, iterators, linked lists, lists, object oriented programming, objects, polymorphism, queues, recursion, sorting, stacks, trees, uml

## ABET Coverage

algorithms and complexity, concepts of programming languages, computer science theory, computer architecture and organization, computing-based systems, general purpose programming language

## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage                           Adjusted Topic               Course
--------------------------------------  ---------------------------  ----------------------------------
algorithms and complexity               abstract complexity          <a href='CMSC256.qmd'>CMSC 256</a>
algorithms and complexity               algorithms                   <a href='CMSC256.qmd'>CMSC 256</a>
algorithms and complexity               basic searching              <a href='CMSC256.qmd'>CMSC 256</a>
algorithms and complexity               binary trees                 <a href='CMSC256.qmd'>CMSC 256</a>
algorithms and complexity               exceptions                   <a href='CMSC256.qmd'>CMSC 256</a>
algorithms and complexity               hash functions               <a href='CMSC256.qmd'>CMSC 256</a>
computer architecture and organization  inheritance                  <a href='CMSC256.qmd'>CMSC 256</a>
computer architecture and organization  object oriented programming  <a href='CMSC256.qmd'>CMSC 256</a>
computer science theory                 exceptions                   <a href='CMSC256.qmd'>CMSC 256</a>
computing-based systems                 interfaces                   <a href='CMSC256.qmd'>CMSC 256</a>
concepts of programming languages       classes                      <a href='CMSC256.qmd'>CMSC 256</a>
concepts of programming languages       data structures              <a href='CMSC256.qmd'>CMSC 256</a>
concepts of programming languages       deques                       <a href='CMSC256.qmd'>CMSC 256</a>
concepts of programming languages       generics                     <a href='CMSC256.qmd'>CMSC 256</a>
concepts of programming languages       graphs                       <a href='CMSC256.qmd'>CMSC 256</a>
concepts of programming languages       iterators                    <a href='CMSC256.qmd'>CMSC 256</a>
concepts of programming languages       linked lists                 <a href='CMSC256.qmd'>CMSC 256</a>
concepts of programming languages       lists                        <a href='CMSC256.qmd'>CMSC 256</a>
concepts of programming languages       objects                      <a href='CMSC256.qmd'>CMSC 256</a>
concepts of programming languages       polymorphism                 <a href='CMSC256.qmd'>CMSC 256</a>
concepts of programming languages       queues                       <a href='CMSC256.qmd'>CMSC 256</a>
concepts of programming languages       recursion                    <a href='CMSC256.qmd'>CMSC 256</a>
concepts of programming languages       sorting                      <a href='CMSC256.qmd'>CMSC 256</a>
concepts of programming languages       stacks                       <a href='CMSC256.qmd'>CMSC 256</a>
concepts of programming languages       trees                        <a href='CMSC256.qmd'>CMSC 256</a>
general purpose programming language    uml                          <a href='CMSC256.qmd'>CMSC 256</a>


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


