---
title: "CMSC 610 - Algorithmic Foundations of Bioinformatics"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; 3 lecture hours. 3 credits. Prerequisite: Graduate student standing or acceptance into five-year accelerated program in computer science or related discipline such as bioinformatics. The purpose of the course is to teach algorithms for analyzing biological and medical data. The focus will be on understanding the inner workings of algorithms used in bioinformatics tools. Topic covered will include algorithms for assembling and searching biological sequences, finding patterns associated with disease, and exploring biological networks.


## Restrictions including pre- or co-requisities
 
Graduate student standing or acceptance into five-year accelerated program in computer science or related discipline such as bioinformatics.

## Description

The purpose of the course is to teach algorithms for analyzing biological and medical data. The focus will be on understanding the inner workings of algorithms used in bioinformatics tools. Topic covered will include algorithms for assembling and searching biological sequences, finding patterns associated with disease, and exploring biological networks.

## Past Syllabii

(none since Spring 2021)

## Topics

algorithms, bioinformatics, biological sequences, data, networks, patterns

## ABET Coverage

algorithms and complexity, techniques, skills, and tools, information management, networking and communication, parallel and distributed computing

## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage                       Adjusted Topic        Course
----------------------------------  --------------------  ----------------------------------
algorithms and complexity           algorithms            <a href='CMSC610.qmd'>CMSC 610</a>
information management              data                  <a href='CMSC610.qmd'>CMSC 610</a>
networking and communication        networks              <a href='CMSC610.qmd'>CMSC 610</a>
parallel and distributed computing  patterns              <a href='CMSC610.qmd'>CMSC 610</a>
techniques, skills, and tools       bioinformatics        <a href='CMSC610.qmd'>CMSC 610</a>
techniques, skills, and tools       biological sequences  <a href='CMSC610.qmd'>CMSC 610</a>


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


