---
title: "CMSC 526 - Theory of Programming Languages"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; 3 lecture hours. 3 credits. Prerequisite: CMSC 403, graduate student standing or acceptance into the five-year accelerated B.S. and M.S. program in computer science. An introduction to the formal semantics of programming languages, logic programming and functional programming. Topics include denotational semantics, attribute grammars, Backus Formal Functional Programming, fixed point semantics, model-theoretic semantics and PROLOG.


## Restrictions including pre- or co-requisities
 
CMSC 403, graduate student standing or acceptance into the five-year accelerated BS and MS program in computer science.

## Description

An introduction to the formal semantics of programming languages, logic programming and functional programming. Topics include denotational semantics, attribute grammars, Backus Formal Functional Programming, fixed point semantics, model-theoretic semantics and PROLOG.

## Past Syllabii

(none since Spring 2021)

## Topics

languages, logic, model-theoretic semtances, semantics

## ABET Coverage

general purpose programming language, techniques, skills, and tools, concepts of programming languages

## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage                         Adjusted Topic             Course
------------------------------------  -------------------------  ----------------------------------
concepts of programming languages     model-theoretic semtances  <a href='CMSC526.qmd'>CMSC 526</a>
concepts of programming languages     semantics                  <a href='CMSC526.qmd'>CMSC 526</a>
general purpose programming language  languages                  <a href='CMSC526.qmd'>CMSC 526</a>
techniques, skills, and tools         logic                      <a href='CMSC526.qmd'>CMSC 526</a>


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


