---
title: "CMSC 491 - Topics in Computer Science"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; variable hours. 1-3 credits. May be repeated for credit with different content. Prerequisite: permission of instructor. This course will cover selected topics in computer science. See the Schedule of Classes for specific topics to be offered each semester.


## Restrictions including pre- or co-requisities
 
permission of instructor.

## Description

This course will cover selected topics in computer science. See the Schedule of Classes for specific topics to be offered each semester.

## Past Syllabii

<a href='./202210/CMSC_491_Syllabus_Fall_2021.pdf'>Fall 2021</a>

## Topics

selected topics

## ABET Coverage



## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage    Adjusted Topic    Course
---------------  ----------------  --------


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


