---
title: "CMSC 409 - Artificial Intelligence"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; 3 lecture hours. 3 credits. Prerequisites: CMSC 401 with a minimum grade of C and MATH 310. Covers problem spaces, problem-solving methods, game playing, knowledge representatives, expert systems, natural language understanding.


## Restrictions including pre- or co-requisities
 
CMSC 401 with a minimum grade of C and MATH 310.

## Description

Covers problem spaces, problem-solving methods, game playing, knowledge representatives, expert systems, natural language understanding.

## Past Syllabii

<a href='./202210/CMSC_409_Syllabus_Fall_2021.pdf'>Fall 2021</a>, <a href='./202310/CMSC_409_Syllabus_Fall_2022.pdf'>Fall 2022</a>

## Topics

expert systems, game playing, knowledge representatives, machine learning, natural language, problem solving, problem spaces

## ABET Coverage

concepts of programming languages, general purpose programming language, techniques, skills, and tools

## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage                         Adjusted Topic             Course
------------------------------------  -------------------------  ----------------------------------
concepts of programming languages     expert systems             <a href='CMSC409.qmd'>CMSC 409</a>
concepts of programming languages     game playing               <a href='CMSC409.qmd'>CMSC 409</a>
concepts of programming languages     knowledge representatives  <a href='CMSC409.qmd'>CMSC 409</a>
general purpose programming language  machine learning           <a href='CMSC409.qmd'>CMSC 409</a>
general purpose programming language  natural language           <a href='CMSC409.qmd'>CMSC 409</a>
techniques, skills, and tools         problem solving            <a href='CMSC409.qmd'>CMSC 409</a>
techniques, skills, and tools         problem spaces             <a href='CMSC409.qmd'>CMSC 409</a>


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


