---
title: "CMSC 510 - Regularization Methods for Machine Learning"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; 3 lecture hours (delivered online, face-to-face or hybrid). 3 credits. Enrollment is restricted to students with graduate standing in computer science or related discipline such as bioinformatics or acceptance into the accelerated B.S. to M.S. program in computer science. The course will assume undergraduate-level background in algorithms, linear algebra, calculus, statistics and probability. Upon successful completion of this course, the student will be able to understand recent advances in machine learning and apply machine-learning tools that go beyond learning from data, as well as have the ability to incorporate additional knowledge about the learning problem. Topics covered will include optimization-based view of supervised machine learning; classical regularization approaches including weight decay and Lasso; regularization terms incorporating additional knowledge about structures in the feature space, including group lasso and graph-based regularization terms; semi-supervised learning using graphs linking unlabeled and labeled samples.


## Restrictions including pre- or co-requisities
 
Enrollment is restricted to students with graduate standing in computer science or related discipline such as bioinformatics or acceptance into the accelerated BS to MS program in computer science.

## Description

The course will assume undergraduate-level background in algorithms, linear algebra, calculus, statistics and probability. Upon successful completion of this course, the student will be able to understand recent advances in machine learning and apply machine-learning tools that go beyond learning from data, as well as have the ability to incorporate additional knowledge about the learning problem. Topics covered will include optimization-based view of supervised machine learning; classical regularization approaches including weight decay and Lasso; regularization terms incorporating additional knowledge about structures in the feature space, including group lasso and graph-based regularization terms; semi-supervised learning using graphs linking unlabeled and labeled samples.

## Past Syllabii

<a href='./202210/CMSC_510_Syllabus_Fall_2021.pdf'>Fall 2021</a>, <a href='./202310/CMSC_510_Syllabus_Fall_2022.pdf'>Fall 2022</a>

## Topics

algorithms, calculus, data analysis, graph algorithms, linear algebra, machine learning, natural language, optimization, probability, regularization, statistics

## ABET Coverage

algorithms and complexity, discrete mathematics, general purpose programming language, concepts of programming languages, probability, statistics

## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage                         Adjusted Topic    Course
------------------------------------  ----------------  ----------------------------------
algorithms and complexity             algorithms        <a href='CMSC510.qmd'>CMSC 510</a>
algorithms and complexity             data analysis     <a href='CMSC510.qmd'>CMSC 510</a>
algorithms and complexity             graph algorithms  <a href='CMSC510.qmd'>CMSC 510</a>
concepts of programming languages     optimization      <a href='CMSC510.qmd'>CMSC 510</a>
concepts of programming languages     regularization    <a href='CMSC510.qmd'>CMSC 510</a>
discrete mathematics                  calculus          <a href='CMSC510.qmd'>CMSC 510</a>
discrete mathematics                  linear algebra    <a href='CMSC510.qmd'>CMSC 510</a>
general purpose programming language  machine learning  <a href='CMSC510.qmd'>CMSC 510</a>
general purpose programming language  natural language  <a href='CMSC510.qmd'>CMSC 510</a>
probability                           probability       <a href='CMSC510.qmd'>CMSC 510</a>
statistics                            statistics        <a href='CMSC510.qmd'>CMSC 510</a>


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


