---
title: "CMSC 455 - Software as a Service"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; 3 lecture hours. 3 credits. Prerequisite: CMSC 355 with a minimum grade of C. Enrollment is restricted to majors in the computer science program. Students will examine the challenges, opportunities and open problems of software-as-a-service deployed on commodity cloud computing platforms. Covers relevant software architectures and API design principles. Includes concepts of modern software frameworks for software development, cloud computing for software deployment and software operations. Students participate in projects that use modern tooling to develop, deploy and monitor a software application.


## Restrictions including pre- or co-requisities
 
CMSC 355 with a minimum grade of C. Enrollment is restricted to majors in the computer science program.

## Description

Students will examine the challenges, opportunities and open problems of software-as-a-service deployed on commodity cloud computing platforms. Covers relevant software architectures and API design principles. Includes concepts of modern software frameworks for software development, cloud computing for software deployment and software operations. Students participate in projects that use modern tooling to develop, deploy and monitor a software application.

## Past Syllabii

<a href='./202210/CMSC_455_Syllabus_Fall_2021.pdf'>Fall 2021</a>, <a href='./202310/CMSC_455_Syllabus_Fall_2022.pdf'>Fall 2022</a>

## Topics

api, applications, cloud computing, software development, software management

## ABET Coverage

concepts of programming languages, software development

## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage                      Adjusted Topic        Course
---------------------------------  --------------------  ----------------------------------
concepts of programming languages  api                   <a href='CMSC455.qmd'>CMSC 455</a>
concepts of programming languages  cloud computing       <a href='CMSC455.qmd'>CMSC 455</a>
software development               applications          <a href='CMSC455.qmd'>CMSC 455</a>
software development               software development  <a href='CMSC455.qmd'>CMSC 455</a>
software development               software management   <a href='CMSC455.qmd'>CMSC 455</a>


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


