---
title: "CMSC 635 - Knowledge Discovery and Data Mining"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; 3 lecture hours (delivered online, face-to-face or hybrid). 3 credits. Prerequisite: CMSC 401 or corequisite: CMSC 501. Enrollment is restricted to students with graduate standing in computer science or a related discipline such as bioinformatics, or those accepted into the accelerated B.S. to M.S. program in computer science. Covers knowledge discovery and data mining concepts, tools and methods; provides hands-on experience based on a project involving analysis of large real-life data. Topics include the knowledge discovery process, data storage and representation, preprocessing algorithms for missing data imputation, feature selection and discretization; unsupervised learning algorithms for clustering and association mining; supervised learning algorithms including decision trees, Bayesian models and introduction to support vector machines and neural networks; ensemble learning; protocols and measures for validation of predictive models; and data security and privacy issues.


## Restrictions including pre- or co-requisities
 
CMSC 401 or corequisite: CMSC 501. Enrollment is restricted to students with graduate standing in computer science or a related discipline such as bioinformatics, or those accepted into the accelerated BS to MS program in computer science.

## Description

Covers knowledge discovery and data mining concepts, tools and methods; provides hands-on experience based on a project involving analysis of large real-life data. Topics include the knowledge discovery process, data storage and representation, preprocessing algorithms for missing data imputation, feature selection and discretization; unsupervised learning algorithms for clustering and association mining; supervised learning algorithms including decision trees, Bayesian models and introduction to support vector machines and neural networks; ensemble learning; protocols and measures for validation of predictive models; and data security and privacy issues.

## Past Syllabii

<a href='./202120/CMSC_635_Syllabus_Spring_2021.pdf'>Spring 2021</a>, <a href='./202220/CMSC_635_Syllabus_Spring_2022.pdf'>Spring 2022</a>, <a href='./202320/CMSC_635_Syllabus_Spring_2023.pdf'>Spring 2023</a>

## Topics

algorithms, analysis, bayesian models, data, data imputation, data mining, data preprocessing, data security, data storage, decision trees, discovery process, discretization, ensemble learning, feature selection, neural networks, real-world applications, security, supervised data analysis, support vector machines, unsupervised data analysis

## ABET Coverage

algorithms and complexity, concepts of programming languages, computer architecture and organization, information management, computer science theory, general purpose programming language, networking and communication, local and global impacts, security and privacy

## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage                           Adjusted Topic              Course
--------------------------------------  --------------------------  ----------------------------------
algorithms and complexity               algorithms                  <a href='CMSC635.qmd'>CMSC 635</a>
algorithms and complexity               analysis                    <a href='CMSC635.qmd'>CMSC 635</a>
algorithms and complexity               supervised data analysis    <a href='CMSC635.qmd'>CMSC 635</a>
algorithms and complexity               support vector machines     <a href='CMSC635.qmd'>CMSC 635</a>
algorithms and complexity               unsupervised data analysis  <a href='CMSC635.qmd'>CMSC 635</a>
computer architecture and organization  data                        <a href='CMSC635.qmd'>CMSC 635</a>
computer science theory                 discretization              <a href='CMSC635.qmd'>CMSC 635</a>
concepts of programming languages       bayesian models             <a href='CMSC635.qmd'>CMSC 635</a>
general purpose programming language    ensemble learning           <a href='CMSC635.qmd'>CMSC 635</a>
general purpose programming language    feature selection           <a href='CMSC635.qmd'>CMSC 635</a>
information management                  data                        <a href='CMSC635.qmd'>CMSC 635</a>
information management                  data imputation             <a href='CMSC635.qmd'>CMSC 635</a>
information management                  data mining                 <a href='CMSC635.qmd'>CMSC 635</a>
information management                  data preprocessing          <a href='CMSC635.qmd'>CMSC 635</a>
information management                  data security               <a href='CMSC635.qmd'>CMSC 635</a>
information management                  data storage                <a href='CMSC635.qmd'>CMSC 635</a>
information management                  decision trees              <a href='CMSC635.qmd'>CMSC 635</a>
information management                  discovery process           <a href='CMSC635.qmd'>CMSC 635</a>
local and global impacts                real-world applications     <a href='CMSC635.qmd'>CMSC 635</a>
networking and communication            neural networks             <a href='CMSC635.qmd'>CMSC 635</a>
security and privacy                    security                    <a href='CMSC635.qmd'>CMSC 635</a>


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


