---
title: "CMSC 420 - Software Project Management"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; 3 lecture hours. 3 credits. Prerequisite: CMSC 355 with a minimum grade of C. Study of the logistics of team software development. Students work in teams to gain experience in software management and develop the components of a larger software product. Topics include risk management, project planning, quality management, configuration management and software testing.


## Restrictions including pre- or co-requisities
 
CMSC 355 with a minimum grade of C.

## Description

Study of the logistics of team software development. Students work in teams to gain experience in software management and develop the components of a larger software product. Topics include risk management, project planning, quality management, configuration management and software testing.

## Past Syllabii

(none since Spring 2021)

## Topics

project planning, quality management, risk management, software development, software management, software quality

## ABET Coverage

techniques, skills, and tools, security and privacy, software development

## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage                  Adjusted Topic        Course
-----------------------------  --------------------  ----------------------------------
security and privacy           risk management       <a href='CMSC420.qmd'>CMSC 420</a>
software development           software development  <a href='CMSC420.qmd'>CMSC 420</a>
software development           software management   <a href='CMSC420.qmd'>CMSC 420</a>
software development           software quality      <a href='CMSC420.qmd'>CMSC 420</a>
techniques, skills, and tools  project planning      <a href='CMSC420.qmd'>CMSC 420</a>
techniques, skills, and tools  quality management    <a href='CMSC420.qmd'>CMSC 420</a>


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


