---
title: "CMSC 101 - Introduction to Computer Science"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; 3 lecture hours. 3 credits. Prerequisite: MATH 139 or MATH 141 with a minimum grade of C. An introduction to the work of computer scientists, including an overview of current research and application areas as well as career opportunities. Topics include problem-solving, the basics of computer organization, the software engineering life cycle, research resources and social and ethical aspects of technology. Additional topics also include binary, hexadecimal, two’s complement, floating point representation, ASCII and Unicode.


## Restrictions including pre- or co-requisities
 
MATH 139 or MATH 141 with a minimum grade of C.

## Description

An introduction to the work of computer scientists, including an overview of current research and application areas as well as career opportunities. Topics include problem-solving, the basics of computer organization, the software engineering life cycle, research resources and social and ethical aspects of technology. Additional topics also include binary, hexadecimal, two’s complement, floating point representation, ASCII and Unicode.

## Past Syllabii

(none since Spring 2021)

## Topics

ascii, basics of computer organization, ethical aspects of technology, numeric representation, problem solving, research resources, social aspects of technology, software engineering life cycle, unicode

## ABET Coverage

computer architecture and organization, security and privacy, statistics, techniques, skills, and tools, networking and communication, software development, computer science theory, local and global impacts, computing-based systems

## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage                           Adjusted Topic                   Course
--------------------------------------  -------------------------------  ----------------------------------
computer architecture and organization  ascii                            <a href='CMSC101.qmd'>CMSC 101</a>
computer architecture and organization  basics of computer organization  <a href='CMSC101.qmd'>CMSC 101</a>
computer science theory                 unicode                          <a href='CMSC101.qmd'>CMSC 101</a>
computing-based systems                 numeric representation           <a href='CMSC101.qmd'>CMSC 101</a>
local and global impacts                ethical aspects of technology    <a href='CMSC101.qmd'>CMSC 101</a>
local and global impacts                social aspects of technology     <a href='CMSC101.qmd'>CMSC 101</a>
networking and communication            research resources               <a href='CMSC101.qmd'>CMSC 101</a>
security and privacy                    ethical aspects of technology    <a href='CMSC101.qmd'>CMSC 101</a>
security and privacy                    social aspects of technology     <a href='CMSC101.qmd'>CMSC 101</a>
software development                    software engineering life cycle  <a href='CMSC101.qmd'>CMSC 101</a>
statistics                              numeric representation           <a href='CMSC101.qmd'>CMSC 101</a>
techniques, skills, and tools           problem solving                  <a href='CMSC101.qmd'>CMSC 101</a>
techniques, skills, and tools           research resources               <a href='CMSC101.qmd'>CMSC 101</a>


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


