---
title: "CMSC 414 - Computer and Network Security"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; 3 lecture hours. 3 credits. Prerequisite: CMSC 401 with a minimum grade of C. Corequisite: CMSC 312. This course covers the best practices of computer systems and network security. Key topics include security architecture, cryptographic systems and security management tools.


## Restrictions including pre- or co-requisities
 
CMSC 401 with a minimum grade of C. Corequisite: CMSC 312.

## Description

This course covers the best practices of computer systems and network security. Key topics include security architecture, cryptographic systems and security management tools.

## Past Syllabii

<a href='./202120/CMSC_414_Syllabus_Spring_2021.pdf'>Spring 2021</a>, <a href='./202220/CMSC_414_Syllabus_Spring_2022.pdf'>Spring 2022</a>, <a href='./202320/CMSC_414_Syllabus_Spring_2023.pdf'>Spring 2023</a>

## Topics

application layer attacks, architecture, computer networks, computer security, computer systems design, cryptographic systems, firewalls, internet, link layer attacks, network penetration, networks, security

## ABET Coverage

security and privacy, computer architecture and organization, software development, networking and communication

## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage                           Adjusted Topic             Course
--------------------------------------  -------------------------  ----------------------------------
computer architecture and organization  architecture               <a href='CMSC414.qmd'>CMSC 414</a>
networking and communication            internet                   <a href='CMSC414.qmd'>CMSC 414</a>
networking and communication            networks                   <a href='CMSC414.qmd'>CMSC 414</a>
security and privacy                    application layer attacks  <a href='CMSC414.qmd'>CMSC 414</a>
security and privacy                    computer networks          <a href='CMSC414.qmd'>CMSC 414</a>
security and privacy                    computer security          <a href='CMSC414.qmd'>CMSC 414</a>
security and privacy                    cryptographic systems      <a href='CMSC414.qmd'>CMSC 414</a>
security and privacy                    firewalls                  <a href='CMSC414.qmd'>CMSC 414</a>
security and privacy                    link layer attacks         <a href='CMSC414.qmd'>CMSC 414</a>
security and privacy                    network penetration        <a href='CMSC414.qmd'>CMSC 414</a>
security and privacy                    security                   <a href='CMSC414.qmd'>CMSC 414</a>
software development                    computer systems design    <a href='CMSC414.qmd'>CMSC 414</a>


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


