---
title: "CMSC 516 - Advanced Natural Language Processing"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; 3 lecture hours (delivered online, face-to-face or hybrid). 3 credits. Enrollment is restricted to students with graduate standing in computer science or a related discipline, or those accepted into the accelerated B.S. to M.S. program in computer science. Upon successful completion of this course, the student will be able to understand recent advances in natural language processing and apply NLP algorithms and techniques for processing unstructured text. Word-level, syntactic and semantic processing will be considered. Specific topics include rule-based and statistical methods for creating computer programs that analyze, generate and understand human language. Regular expressions and automata, context-free grammars, probabilistic classifiers and machine learning. Applications to real-world problems such as spell-checking, Web search, automatic question answering, authorship identification and developing conversational interfaces.


## Restrictions including pre- or co-requisities
 
Enrollment is restricted to students with graduate standing in computer science or a related discipline, or those accepted into the accelerated BS to MS program in computer science.

## Description

Upon successful completion of this course, the student will be able to understand recent advances in natural language processing and apply NLP algorithms and techniques for processing unstructured text. Word-level, syntactic and semantic processing will be considered. Specific topics include rule-based and statistical methods for creating computer programs that analyze, generate and understand human language. Regular expressions and automata, context-free grammars, probabilistic classifiers and machine learning. Applications to real-world problems such as spell-checking, Web search, automatic question answering, authorship identification and developing conversational interfaces.

## Past Syllabii

<a href='./202210/CMSC_516_Syllabus_Fall_2021.pdf'>Fall 2021</a>, <a href='./202310/CMSC_516_Syllabus_Fall_2022.pdf'>Fall 2022</a>, <a href='./202320/CMSC_516_Syllabus_Spring_2023.pdf'>Spring 2023</a>

## Topics

automation, context-free grammars, machine learning, natural language, nlp algorithms, probabilistic classifiers, regular expressions, semantics, statistics, syntax

## ABET Coverage

techniques, skills, and tools, concepts of programming languages, general purpose programming language, algorithms and complexity, probability, statistics

## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage                         Adjusted Topic             Course
------------------------------------  -------------------------  ----------------------------------
algorithms and complexity             nlp algorithms             <a href='CMSC516.qmd'>CMSC 516</a>
concepts of programming languages     context-free grammars      <a href='CMSC516.qmd'>CMSC 516</a>
concepts of programming languages     regular expressions        <a href='CMSC516.qmd'>CMSC 516</a>
concepts of programming languages     semantics                  <a href='CMSC516.qmd'>CMSC 516</a>
concepts of programming languages     syntax                     <a href='CMSC516.qmd'>CMSC 516</a>
general purpose programming language  machine learning           <a href='CMSC516.qmd'>CMSC 516</a>
general purpose programming language  natural language           <a href='CMSC516.qmd'>CMSC 516</a>
probability                           probabilistic classifiers  <a href='CMSC516.qmd'>CMSC 516</a>
statistics                            statistics                 <a href='CMSC516.qmd'>CMSC 516</a>
techniques, skills, and tools         automation                 <a href='CMSC516.qmd'>CMSC 516</a>


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


