---
title: "CMSC 255 - Introduction to Programming"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; 3 lecture and 2 laboratory hours. 4 credits. Prerequisite: calculus-level placement on the VCU Mathematics Placement Test within the one-year period immediately preceding enrollment in the course, or MATH 151 or equivalent. Students are expected to have fundamental computer skills. Introduction to object-oriented programming using Java. Topics include problem-solving, top-down design of algorithms using control structures, methods, arrays, basic I/O, basic concepts of objects and classes in Java, Java classes for manipulating strings, and introduction to program testing, UML notation and integrated development environments. Students may not receive credit for both CMSC 255 and INFO 250.


## Restrictions including pre- or co-requisities
 
calculus-level placement on the VCU Mathematics Placement Test within the one-year period immediately preceding enrollment in the course, or MATH 151 or equivalent. Students are expected to have fundamental computer skills.

## Description

Introduction to object-oriented programming using Java. Topics include problem-solving, top-down design of algorithms using control structures, methods, arrays, basic I/O, basic concepts of objects and classes in Java, Java classes for manipulating strings, and introduction to program testing, UML notation and integrated development environments. Students may not receive credit for both CMSC 255 and INFO 250.

## Past Syllabii

<a href='./202120/CMSC_255_Syllabus_Spring_2021.pdf'>Spring 2021</a>, <a href='./202210/CMSC_255_Syllabus_Fall_2021.pdf'>Fall 2021</a>, <a href='./202220/CMSC_255_Syllabus_Spring_2022.pdf'>Spring 2022</a>, <a href='./202310/CMSC_255_Syllabus_Fall_2022.pdf'>Fall 2022</a>, <a href='./202320/CMSC_255_Syllabus_Spring_2023.pdf'>Spring 2023</a>

## Topics

algorithms, arrays, classes, computers, control structures, ide, input/output, java, methods, objects, problem solving, program testing, simple data types, strings, syntax, top down design, uml

## ABET Coverage

algorithms and complexity, concepts of programming languages, operating systems, techniques, skills, and tools, computer science theory, general purpose programming language, software development

## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage                         Adjusted Topic      Course
------------------------------------  ------------------  ----------------------------------
algorithms and complexity             algorithms          <a href='CMSC255.qmd'>CMSC 255</a>
computer science theory               top down design     <a href='CMSC255.qmd'>CMSC 255</a>
concepts of programming languages     arrays              <a href='CMSC255.qmd'>CMSC 255</a>
concepts of programming languages     classes             <a href='CMSC255.qmd'>CMSC 255</a>
concepts of programming languages     control structures  <a href='CMSC255.qmd'>CMSC 255</a>
concepts of programming languages     input/output        <a href='CMSC255.qmd'>CMSC 255</a>
concepts of programming languages     methods             <a href='CMSC255.qmd'>CMSC 255</a>
concepts of programming languages     objects             <a href='CMSC255.qmd'>CMSC 255</a>
concepts of programming languages     problem solving     <a href='CMSC255.qmd'>CMSC 255</a>
concepts of programming languages     simple data types   <a href='CMSC255.qmd'>CMSC 255</a>
concepts of programming languages     strings             <a href='CMSC255.qmd'>CMSC 255</a>
concepts of programming languages     syntax              <a href='CMSC255.qmd'>CMSC 255</a>
general purpose programming language  uml                 <a href='CMSC255.qmd'>CMSC 255</a>
operating systems                     computers           <a href='CMSC255.qmd'>CMSC 255</a>
operating systems                     java                <a href='CMSC255.qmd'>CMSC 255</a>
software development                  ide                 <a href='CMSC255.qmd'>CMSC 255</a>
techniques, skills, and tools         ide                 <a href='CMSC255.qmd'>CMSC 255</a>
techniques, skills, and tools         program testing     <a href='CMSC255.qmd'>CMSC 255</a>


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


