---
title: "CMSC 435 - Introduction to Data Science"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; 3 lecture hours. 3 credits. Prerequisite: CMSC 401 with a minimum grade of C. This course covers understanding, representation, storage, retrieval, preprocessing and analysis of data. Specific topics include data quality and preprocessing, database management systems, data warehouses, selected methods for scalable unsupervised and supervised data analysis, and assessment of results generated by these methods. Students will be engaged in analysis of real-life data from data preprocessing, through data analysis, to the assessment of a knowledge product.


## Restrictions including pre- or co-requisities
 
CMSC 401 with a minimum grade of C.

## Description

This course covers understanding, representation, storage, retrieval, preprocessing and analysis of data. Specific topics include data quality and preprocessing, database management systems, data warehouses, selected methods for scalable unsupervised and supervised data analysis, and assessment of results generated by these methods. Students will be engaged in analysis of real-life data from data preprocessing, through data analysis, to the assessment of a knowledge product.

## Past Syllabii

<a href='./202210/CMSC_435_Syllabus_Fall_2021.pdf'>Fall 2021</a>, <a href='./202310/CMSC_435_Syllabus_Fall_2022.pdf'>Fall 2022</a>

## Topics

analysis, data, data analysis, data quality, data structures, database

## ABET Coverage

algorithms and complexity, information management

## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage              Adjusted Topic    Course
-------------------------  ----------------  ----------------------------------
algorithms and complexity  analysis          <a href='CMSC435.qmd'>CMSC 435</a>
information management     data              <a href='CMSC435.qmd'>CMSC 435</a>
information management     data analysis     <a href='CMSC435.qmd'>CMSC 435</a>
information management     data quality      <a href='CMSC435.qmd'>CMSC 435</a>
information management     data structures   <a href='CMSC435.qmd'>CMSC 435</a>
information management     database          <a href='CMSC435.qmd'>CMSC 435</a>


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


