---
title: "CMSC 312 - Introduction to Operating Systems"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; 3 lecture hours. 3 credits. Prerequisite: CMSC 311 or EGRE 364. Computer systems design, I/O processing, secondary memory organization, command languages, memory management and job scheduling. Students will work in teams to design and implement an operating system simulation.


## Restrictions including pre- or co-requisities
 
CMSC 311 or EGRE 364.

## Description

Computer systems design, I/O processing, secondary memory organization, command languages, memory management and job scheduling. Students will work in teams to design and implement an operating system simulation.

## Past Syllabii

<a href='./202120/CMSC_312_Syllabus_Spring_2021.pdf'>Spring 2021</a>, <a href='./202210/CMSC_312_Syllabus_Fall_2021.pdf'>Fall 2021</a>, <a href='./202220/CMSC_312_Syllabus_Spring_2022.pdf'>Spring 2022</a>, <a href='./202310/CMSC_312_Syllabus_Fall_2022.pdf'>Fall 2022</a>, <a href='./202320/CMSC_312_Syllabus_Spring_2023.pdf'>Spring 2023</a>

## Topics

command languages, computer systems design, concurrency, debugging, distributed systems, file management, input/output, job scheduling, memory management, operating systems, process scheduling, secondary memory

## ABET Coverage

general purpose programming language, concepts of programming languages, parallel and distributed computing, information management, networking and communication, operating systems

## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage                         Adjusted Topic           Course
------------------------------------  -----------------------  ----------------------------------
concepts of programming languages     computer systems design  <a href='CMSC312.qmd'>CMSC 312</a>
concepts of programming languages     concurrency              <a href='CMSC312.qmd'>CMSC 312</a>
concepts of programming languages     debugging                <a href='CMSC312.qmd'>CMSC 312</a>
concepts of programming languages     input/output             <a href='CMSC312.qmd'>CMSC 312</a>
concepts of programming languages     process scheduling       <a href='CMSC312.qmd'>CMSC 312</a>
general purpose programming language  command languages        <a href='CMSC312.qmd'>CMSC 312</a>
information management                file management          <a href='CMSC312.qmd'>CMSC 312</a>
information management                memory management        <a href='CMSC312.qmd'>CMSC 312</a>
networking and communication          job scheduling           <a href='CMSC312.qmd'>CMSC 312</a>
operating systems                     operating systems        <a href='CMSC312.qmd'>CMSC 312</a>
operating systems                     secondary memory         <a href='CMSC312.qmd'>CMSC 312</a>
parallel and distributed computing    distributed systems      <a href='CMSC312.qmd'>CMSC 312</a>


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


