---
title: "CMSC 512 - Advanced Social Network Analysis and Security"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; 3 lecture hours (delivered online, face-to-face or hybrid). 3 credits. Pre- or corequisites: CMSC 412 and CMSC 501. Enrollment is restricted to students with graduate standing in computer science or a related discipline such as bioinformatics or acceptance into the accelerated B.S. to M.S. program in computer science. The purpose of the course is to teach algorithms for analyzing social networks and complex systems. The focus will be on understanding the inner workings of algorithms using in-network analysis and security threats in online social network sites. Topic covered will include modeling social and technological networks, methods for analyzing structure and dynamical processes on the network, and security and privacy issues in online social networks such as inference attacks, network anonymization, sybil attacks and defense, social bots.


## Restrictions including pre- or co-requisities
 
CMSC 412 and CMSC 501. Enrollment is restricted to students with graduate standing in computer science or a related discipline such as bioinformatics or acceptance into the accelerated BS to MS program in computer science.

## Description

The purpose of the course is to teach algorithms for analyzing social networks and complex systems. The focus will be on understanding the inner workings of algorithms using in-network analysis and security threats in online social network sites. Topic covered will include modeling social and technological networks, methods for analyzing structure and dynamical processes on the network, and security and privacy issues in online social networks such as inference attacks, network anonymization, sybil attacks and defense, social bots.

## Past Syllabii

<a href='./202120/CMSC_512_Syllabus_Spring_2021.pdf'>Spring 2021</a>, <a href='./202220/CMSC_512_Syllabus_Spring_2022.pdf'>Spring 2022</a>, <a href='./202320/CMSC_512_Syllabus_Spring_2023.pdf'>Spring 2023</a>

## Topics

algorithms, analysis, networks, security, social network

## ABET Coverage

algorithms and complexity, networking and communication, security and privacy

## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage                 Adjusted Topic    Course
----------------------------  ----------------  ----------------------------------
algorithms and complexity     algorithms        <a href='CMSC512.qmd'>CMSC 512</a>
algorithms and complexity     analysis          <a href='CMSC512.qmd'>CMSC 512</a>
networking and communication  networks          <a href='CMSC512.qmd'>CMSC 512</a>
networking and communication  social network    <a href='CMSC512.qmd'>CMSC 512</a>
security and privacy          security          <a href='CMSC512.qmd'>CMSC 512</a>


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


