---
title: "CMSC 502 - Parallel Algorithms"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; 3 lecture hours (delivered online, face-to-face or hybrid). 3 credits. Prerequisites: CMSC 312 and CMSC 401. Enrollment is restricted to students with graduate standing or those accepted into the accelerated B.S. to M.S. program in computer science. Software and hardware mechanisms for providing mutual exclusion in uniprocessor and multiprocessor environments. Architectural issues including pipeline design, superscalar computers, multiprocessors, memory systems, peripherals, interfacing techniques, networks, performance and software issues. Design and uses of parallel algorithms to solve concurrency problems in a distributed environment including message passing and remote procedure calls. Students will work in teams (as well as on individual projects) to design and implement parallel algorithms.


## Restrictions including pre- or co-requisities
 
CMSC 312 and CMSC 401. Enrollment is restricted to students with graduate standing or those accepted into the accelerated BS to MS program in computer science.

## Description

Software and hardware mechanisms for providing mutual exclusion in uniprocessor and multiprocessor environments. Architectural issues including pipeline design, superscalar computers, multiprocessors, memory systems, peripherals, interfacing techniques, networks, performance and software issues. Design and uses of parallel algorithms to solve concurrency problems in a distributed environment including message passing and remote procedure calls. Students will work in teams (as well as on individual projects) to design and implement parallel algorithms.

## Past Syllabii

<a href='./202210/CMSC_502_Syllabus_Fall_2021.pdf'>Fall 2021</a>, <a href='./202310/CMSC_502_Syllabus_Fall_2022.pdf'>Fall 2022</a>

## Topics

concurrency, interfaces, networks, parallel algorithms, software quality

## ABET Coverage

concepts of programming languages, networking and communication, parallel and distributed computing, software development

## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage                       Adjusted Topic       Course
----------------------------------  -------------------  ----------------------------------
concepts of programming languages   concurrency          <a href='CMSC502.qmd'>CMSC 502</a>
concepts of programming languages   interfaces           <a href='CMSC502.qmd'>CMSC 502</a>
networking and communication        networks             <a href='CMSC502.qmd'>CMSC 502</a>
parallel and distributed computing  parallel algorithms  <a href='CMSC502.qmd'>CMSC 502</a>
software development                software quality     <a href='CMSC502.qmd'>CMSC 502</a>


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


