---
title: "CMSC 413 - Introduction to Cybersecurity"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; 3 lecture hours. 3 credits. Prerequisite: CMSC 401 with a minimum grade of C. This course provides introduction and basic concepts of computer security, cyber attacks, cyber defense, cyber forensics and cyber ethics.


## Restrictions including pre- or co-requisities
 
CMSC 401 with a minimum grade of C.

## Description

This course provides introduction and basic concepts of computer security, cyber attacks, cyber defense, cyber forensics and cyber ethics.

## Past Syllabii

<a href='./202210/CMSC_413_Syllabus_Fall_2021.pdf'>Fall 2021</a>, <a href='./202310/CMSC_413_syllabus_Fall_2022.pdf'>Fall 2022</a>

## Topics

cyber defense, cyber ethics, cyber forensics, cybersecurity, security

## ABET Coverage

security and privacy

## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage         Adjusted Topic    Course
--------------------  ----------------  ----------------------------------
security and privacy  cyber defense     <a href='CMSC413.qmd'>CMSC 413</a>
security and privacy  cyber ethics      <a href='CMSC413.qmd'>CMSC 413</a>
security and privacy  cyber forensics   <a href='CMSC413.qmd'>CMSC 413</a>
security and privacy  cybersecurity     <a href='CMSC413.qmd'>CMSC 413</a>
security and privacy  security          <a href='CMSC413.qmd'>CMSC 413</a>


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


