---
title: "CMSC 702 - Computer Science Seminar"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; 1 seminar hour. 1 credit. May be repeated for credit. Enrollment restricted to students in the doctoral program in computer science. Students will attend a weekly research seminar in which the topic and speaker will change each week in order to cover a broad range of subjects at the forefront of computer science research. Students will have to present and to write a report on at least one seminar presented by other speakers. The objective is to expose students to research topics and scholars in the field of computer science as well as to provide them experience in delivering and critiquing seminar talks. Graded as satisfactory/unsatisfactory.


## Restrictions including pre- or co-requisities
 
Enrollment restricted to students in the doctoral program in computer science. Students will attend a week

## Description

Students will attend a weekly research seminar in which the topic and speaker will change each week in order to cover a broad range of subjects at the forefront of computer science research. Students will have to present and to write a report on at least one seminar presented by other speakers. The objective is to expose students to research topics and scholars in the field of computer science as well as to provide them experience in delivering and critiquing seminar talks. Graded as satisfactory/unsatisfactory.

## Past Syllabii

(none since Spring 2021)

## Topics

research, seminar

## ABET Coverage

concepts of programming languages

## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage                      Adjusted Topic    Course
---------------------------------  ----------------  ----------------------------------
concepts of programming languages  research          <a href='CMSC702.qmd'>CMSC 702</a>
concepts of programming languages  seminar           <a href='CMSC702.qmd'>CMSC 702</a>


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


