---
title: "CMSC 245 - Introduction to Programming Using C++"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; 3 lecture hours. 3 credits. Prerequisite: MATH 151 or satisfactory score on the Mathematical Placement Test. Students registering for CMSC 245 must have taken the VCU Mathematics Placement Test within the one-year period immediately preceding the beginning of the course. An exception to this policy is made in the case in which the stated alternative prerequisite course has been completed at VCU. Students are expected to have fundamental computer skills. Introduction to the concepts and practice of structured programming using C++. Problem-solving, top-down design of algorithms, objects, basic C++ syntax, control structures, functions and arrays. This course is intended for engineering majors.


## Restrictions including pre- or co-requisities
 
MATH 151 or satisfactory score on the Mathematical Placement Test. Students registering for CMSC 245 must have taken the VCU Mathematics Placement Test within the one-year period immediately preceding the beginning of the course. An exception to this policy is made in the case in which the stated alternative prerequisite course has been completed at VCU. Students are expected to have fundamental computer skills.

## Description

Introduction to the concepts and practice of structured programming using C++. Problem-solving, top-down design of algorithms, objects, basic C++ syntax, control structures, functions and arrays. This course is intended for engineering majors.

## Past Syllabii

(none since Spring 2021)

## Topics

arrays, c++ syntax, control structures, functions, problem solving, top down design

## ABET Coverage

concepts of programming languages, algorithms and complexity, computer science theory, software development

## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage                      Adjusted Topic      Course
---------------------------------  ------------------  ----------------------------------
algorithms and complexity          control structures  <a href='CMSC245.qmd'>CMSC 245</a>
computer science theory            problem solving     <a href='CMSC245.qmd'>CMSC 245</a>
concepts of programming languages  arrays              <a href='CMSC245.qmd'>CMSC 245</a>
concepts of programming languages  c++ syntax          <a href='CMSC245.qmd'>CMSC 245</a>
concepts of programming languages  functions           <a href='CMSC245.qmd'>CMSC 245</a>
software development               top down design     <a href='CMSC245.qmd'>CMSC 245</a>


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


