---
title: "CMSC 621 - Theory of Computation"
date: last-modified
format:
  html:
    toc: true
---

## Catalog Description

Semester course; 3 lecture hours. 3 credits. Prerequisite: graduate student standing and permission of instructor. Discussion of the complexity and computability of problems and programs. Topics will include unsolvability, universal programs and abstract complexity.


## Restrictions including pre- or co-requisities
 
graduate student standing and permission of instructor.

## Description

Discussion of the complexity and computability of problems and programs. Topics will include unsolvability, universal programs and abstract complexity.

## Past Syllabii

(none since Spring 2021)

## Topics



## ABET Coverage



## Coverage and Topics Map

Note that topics without associated ABET category assignments are excluded from this map.  See the [mapping](https://docs.google.com/spreadsheets/d/1qrN3L7eRLsM-aVMHYaLQN-FMYtrTJf0_h6dLKlUdPkk/edit#gid=338318647) for more details.

ABET coverage    Adjusted Topic    Course
---------------  ----------------  --------


## Syllabus Statements

Students should visit the URL below and review all syllabus statement information. The full university syllabus statement includes information on safety, registration, the VCU Honor Code, student conduct, withdrawal and more.

*<https://provost.vcu.edu/faculty/faculty-resources/syllabus/#statements>*


